from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import ane_cpu_metal_projection_triad as triad


def test_config_binds_exact_q_projection_and_fail_closed_gates() -> None:
    config = triad.load_config(
        ROOT / "configs/ane_cpu_metal_projection_triad.json"
    )
    assert config["enabled"] is False
    assert config["shape"]["rows"] == 2048
    assert config["shape"]["input_channels"] == 512
    assert config["shape"]["output_channels"] == 512
    assert config["execution"]["qualification_steps"] == 64
    assert "no_intermediate_python_or_numpy_round_trip" in (
        config["adoption_gates"]
    )
    assert config["canonical_checkpoint_mutated"] is False


def test_compare_counts_only_deltas_above_predeclared_tolerance() -> None:
    observed = np.asarray([0.0, 1.001, 2.1], dtype=np.float32)
    reference = np.asarray([0.0, 1.0, 2.0], dtype=np.float32)
    result = triad.compare(observed, reference, tolerance=0.01)
    assert result["mismatch_count"] == 1
    assert result["maximum_absolute_delta"] == pytest.approx(0.1)


def test_timing_summary_requires_positive_repeats() -> None:
    with pytest.raises(triad.TriadFault, match="finite_and_positive"):
        triad.timing_summary([0.1, 0.0])
    summary = triad.timing_summary([0.001, 0.003])
    assert summary["median_milliseconds"] == pytest.approx(2.0)


def test_checked_in_report_remains_nonproduction_when_public_bridges_exist() -> None:
    report_path = ROOT / "reports/ane_cpu_metal_projection_triad_m1.json"
    if not report_path.is_file():
        pytest.skip("hardware report is generated by the M1 qualification")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report["production_eligible"] is False
    assert report["bridge_contract"]["hot_step_python_control"] is True
    assert report["bridge_contract"]["coreml_numpy_input_output"] is True
    assert (
        report["gates"]["no_intermediate_python_or_numpy_round_trip"]
        is False
    )
