"""Supplemental private residual templates for focused Code LM repair.

Keep new targeted repair families here so the main template bank does not grow
into a single unbounded editing surface.
"""

from __future__ import annotations

from typing import Any


def algorithmic_planning_boundary_templates() -> list[dict[str, Any]]:
    return [
        {
            "category": "private_algorithm_weighted_run_summary",
            "prompt": "Return the start index, end index, and sum of the highest-sum contiguous run of positive numbers. Return (-1, -1, 0) when no positive run exists.",
            "entry": "private_algorithm_weighted_run_summary",
            "body": "best = (-1, -1, 0)\nstart = None\ntotal = 0\nfor idx, value in enumerate(data):\n    if value > 0:\n        if start is None:\n            start = idx\n            total = 0\n        total += value\n        candidate = (start, idx, total)\n        if candidate[2] > best[2] or (candidate[2] == best[2] and start < best[0]):\n            best = candidate\n    else:\n        start = None\n        total = 0\nreturn best",
            "cases": [([0, 2, 3, -1, 4], None, (1, 2, 5)), ([-1, 0, -2], None, (-1, -1, 0)), ([1, 1, 0, 2], None, (0, 1, 2)), ([3, -1, 3], None, (0, 0, 3))],
            "tags": ["algorithm_choice", "algorithmic_planning", "state_machine", "return_shape", "edge_case"],
            "residual_concept": "algorithmic_planning",
            "concept_residual_label": "segmented_state_machine_plan_missing",
            "return_shape": "tuple",
            "type_family": "stateful_sequence_algorithm",
            "argument_roles": {"data": "sequence[number]"},
            "required_constructs": ["loop", "branch", "locals", "algorithmic_planning", "edge_conditions"],
            "skeleton_bias": ["single_pass_state_machine", "tie_breaking", "tuple_return_contract"],
            "repair_strategy": "if the decoder emits a plain max sum, force it to carry start/end state and return the full tuple contract",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_algorithm_component_sizes",
            "prompt": "Return sorted connected-component sizes for an undirected edge list over the supplied node set.",
            "entry": "private_algorithm_component_sizes",
            "body": "nodes = list(other)\ngraph = {node: [] for node in nodes}\nfor left, right in data:\n    graph.setdefault(left, []).append(right)\n    graph.setdefault(right, []).append(left)\nseen = set()\nsizes = []\nfor node in nodes:\n    if node in seen:\n        continue\n    stack = [node]\n    seen.add(node)\n    size = 0\n    while stack:\n        current = stack.pop()\n        size += 1\n        for nxt in graph.get(current, []):\n            if nxt not in seen:\n                seen.add(nxt)\n                stack.append(nxt)\n    sizes.append(size)\nreturn sorted(sizes)",
            "cases": [([(1, 2), (3, 4)], [1, 2, 3, 4, 5], [1, 2, 2]), ([], ["a", "b"], [1, 1]), ([(1, 2), (2, 3)], [1, 2, 3], [3]), ([(1, 1)], [1], [1])],
            "tags": ["algorithm_choice", "algorithmic_planning", "graph", "while_loop", "return_shape"],
            "residual_concept": "algorithmic_planning",
            "concept_residual_label": "graph_component_plan_missing",
            "return_shape": "list",
            "type_family": "graph_search_algorithm",
            "argument_roles": {"data": "sequence[edge]", "other": "node_set"},
            "required_constructs": ["loop", "branch", "locals", "algorithmic_planning", "collection_ops"],
            "skeleton_bias": ["adjacency_build", "stack_or_queue_search", "sorted_list_return"],
            "repair_strategy": "if graph candidates only test reachability, require a component accumulation loop over all supplied nodes",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_algorithm_bucketed_intervals",
            "prompt": "Return interval buckets by label after merging each label's overlapping half-open intervals.",
            "entry": "private_algorithm_bucketed_intervals",
            "body": "buckets = {}\nfor label, start, end in data:\n    if end <= start:\n        continue\n    buckets.setdefault(label, []).append((start, end))\nout = {}\nfor label, intervals in buckets.items():\n    merged = []\n    for start, end in sorted(intervals):\n        if not merged or start > merged[-1][1]:\n            merged.append([start, end])\n        else:\n            merged[-1][1] = max(merged[-1][1], end)\n    out[label] = [tuple(item) for item in merged]\nreturn out",
            "cases": [([("a", 1, 3), ("a", 2, 4), ("b", 0, 1)], None, {"a": [(1, 4)], "b": [(0, 1)]}), ([("x", 5, 5)], None, {}), ([("a", 1, 2), ("a", 3, 4)], None, {"a": [(1, 2), (3, 4)]}), ([], None, {})],
            "tags": ["algorithm_choice", "algorithmic_planning", "intervals", "dict", "return_shape"],
            "residual_concept": "algorithmic_planning",
            "concept_residual_label": "grouped_interval_merge_plan_missing",
            "return_shape": "dict",
            "type_family": "grouped_interval_algorithm",
            "argument_roles": {"data": "sequence[label,start,end]"},
            "required_constructs": ["loop", "branch", "locals", "algorithmic_planning", "collection_ops"],
            "skeleton_bias": ["group_then_merge", "invalid_interval_guard", "dict_of_lists_return"],
            "repair_strategy": "if interval candidates merge globally, force grouped planning before per-label merge and dict reconstruction",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_algorithm_two_pointer_limit",
            "prompt": "Return the longest contiguous span with sum at most a non-negative limit, preferring the earliest span on ties.",
            "entry": "private_algorithm_two_pointer_limit",
            "body": "limit = other\nleft = 0\ntotal = 0\nbest = (0, -1, 0)\nfor right, value in enumerate(data):\n    total += value\n    while left <= right and total > limit:\n        total -= data[left]\n        left += 1\n    length = right - left + 1\n    if length > best[2]:\n        best = (left, right, length)\nreturn best",
            "cases": [([2, 1, 3, 1], 4, (0, 1, 2)), ([5, 1, 1], 2, (1, 2, 2)), ([], 3, (0, -1, 0)), ([1, 1, 1], 3, (0, 2, 3))],
            "tags": ["algorithm_choice", "algorithmic_planning", "sliding_window", "two_pointer", "return_shape"],
            "residual_concept": "algorithmic_planning",
            "concept_residual_label": "two_pointer_contract_plan_missing",
            "return_shape": "tuple",
            "type_family": "two_pointer_window_algorithm",
            "argument_roles": {"data": "sequence[nonnegative_number]", "other": "limit"},
            "required_constructs": ["loop", "branch", "locals", "algorithmic_planning", "edge_conditions"],
            "skeleton_bias": ["two_pointer_window", "while_shrink_loop", "earliest_tuple_return"],
            "repair_strategy": "if the decoder brute-forces or returns only length, require carried left/right state and tuple return contract",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
    ]


def type_return_shape_boundary_templates() -> list[dict[str, Any]]:
    return [
        {
            "category": "private_type_boundary_numeric_total",
            "prompt": "Return the numeric total from a scalar, sequence, or mapping. Ignore booleans and non-numeric values.",
            "entry": "private_type_boundary_numeric_total",
            "body": "items = []\nif isinstance(data, dict):\n    items = list(data.values())\nelif isinstance(data, (list, tuple, set)):\n    items = list(data)\nelse:\n    items = [data]\ntotal = 0\nfor item in items:\n    if isinstance(item, bool):\n        continue\n    if isinstance(item, (int, float)):\n        total += item\nreturn total",
            "cases": [([1, 2, "x"], None, 3), ({"a": 2, "b": True, "c": 4.5}, None, 6.5), (7, None, 7), ("bad", None, 0)],
            "tags": ["type_contract_v2", "type_semantic_transfer", "type_family_handling", "return_shape", "scalar_collection_boundary"],
            "residual_concept": "type_semantic_transfer",
            "concept_residual_label": "scalar_collection_numeric_return_contract",
            "return_shape": "number",
            "type_family": "heterogeneous_numeric_contract",
            "argument_roles": {"data": "scalar|sequence|mapping"},
            "required_constructs": ["branch", "loop", "locals", "type_and_return_shape"],
            "skeleton_bias": ["scalar_or_collection_dispatch", "bool_exclusion", "literal_numeric_return"],
            "repair_strategy": "if the decoder confuses scalar and iterable inputs, dispatch on mapping/sequence/scalar before accumulating numeric values",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_type_boundary_string_tokens",
            "prompt": "Return normalized text tokens from a string, bytes, or sequence. Non-text items are skipped.",
            "entry": "private_type_boundary_string_tokens",
            "body": "if isinstance(data, bytes):\n    raw_items = [data.decode('utf-8', errors='ignore')]\nelif isinstance(data, str):\n    raw_items = [data]\nelif isinstance(data, (list, tuple, set)):\n    raw_items = list(data)\nelse:\n    raw_items = []\nout = []\nfor item in raw_items:\n    if isinstance(item, bytes):\n        item = item.decode('utf-8', errors='ignore')\n    if not isinstance(item, str):\n        continue\n    for token in item.lower().replace(',', ' ').split():\n        if token:\n            out.append(token)\nreturn out",
            "cases": [("Hi, YOU", None, ["hi", "you"]), ([b"A b", "C", 3], None, ["a", "b", "c"]), (None, None, []), (b"One", None, ["one"])],
            "tags": ["type_contract_v2", "type_semantic_transfer", "type_family_handling", "return_shape", "string_parser"],
            "residual_concept": "type_semantic_transfer",
            "concept_residual_label": "text_bytes_sequence_list_return_contract",
            "return_shape": "list",
            "type_family": "string_indexing",
            "argument_roles": {"data": "str|bytes|sequence[Any]"},
            "required_constructs": ["branch", "loop", "locals", "index_or_string_ops", "type_and_return_shape"],
            "skeleton_bias": ["text_type_dispatch", "bytes_decode_guard", "list_return_builder"],
            "repair_strategy": "if text candidates crash on bytes or sequences, normalize input family first and return a literal list of tokens",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_type_boundary_mapping_labels",
            "prompt": "Return a dictionary from labels to integer counts, accepting either mappings or records with label/count fields.",
            "entry": "private_type_boundary_mapping_labels",
            "body": "records = []\nif isinstance(data, dict):\n    for key, value in data.items():\n        records.append({'label': key, 'count': value})\nelif isinstance(data, (list, tuple)):\n    records = list(data)\nout = {}\nfor record in records:\n    if not isinstance(record, dict):\n        continue\n    label = record.get('label')\n    count = record.get('count', 0)\n    if label is None:\n        continue\n    try:\n        amount = int(count)\n    except Exception:\n        amount = 0\n    out[str(label)] = out.get(str(label), 0) + amount\nreturn out",
            "cases": [({"a": 2, "b": "3"}, None, {"a": 2, "b": 3}), ([{"label": "x", "count": 2}, {"label": "x", "count": "4"}], None, {"x": 6}), ([1, {"count": 3}], None, {}), (None, None, {})],
            "tags": ["type_contract_v2", "type_semantic_transfer", "type_family_handling", "return_shape", "dict"],
            "residual_concept": "type_semantic_transfer",
            "concept_residual_label": "mapping_or_record_dict_return_contract",
            "return_shape": "dict",
            "type_family": "collection_logic",
            "argument_roles": {"data": "mapping|sequence[record]"},
            "required_constructs": ["branch", "loop", "locals", "collection_ops", "type_and_return_shape"],
            "skeleton_bias": ["mapping_or_record_dispatch", "guarded_int_parse", "literal_dict_return"],
            "repair_strategy": "if candidates return a list of pairs or scalar count, force dict accumulation after mapping/record dispatch",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
    ]


def parsing_encoding_boundary_templates() -> list[dict[str, Any]]:
    return [
        {
            "category": "private_parse_encoding_utf8_lines",
            "prompt": "Return stripped non-empty UTF-8 lines from text or bytes, ignoring undecodable bytes.",
            "entry": "private_parse_encoding_utf8_lines",
            "body": "if isinstance(data, bytes):\n    text = data.decode('utf-8', errors='ignore')\nelif isinstance(data, str):\n    text = data\nelse:\n    return []\nout = []\nfor line in text.replace('\\r\\n', '\\n').replace('\\r', '\\n').split('\\n'):\n    item = line.strip()\n    if item:\n        out.append(item)\nreturn out",
            "cases": [(b"alpha\n\xffbeta\n", None, ["alpha", "beta"]), (" a \r\n\n b ", None, ["a", "b"]), (None, None, []), ("", None, [])],
            "tags": ["parsing_encoding_v1", "parsing", "encoding", "bytes_decode", "return_shape"],
            "residual_concept": "parsing_encoding_v1",
            "concept_residual_label": "utf8_decode_line_boundary",
            "return_shape": "list",
            "type_family": "string_indexing",
            "argument_roles": {"data": "str|bytes"},
            "required_constructs": ["branch", "loop", "locals", "index_or_string_ops", "type_and_return_shape"],
            "skeleton_bias": ["bytes_decode_guard", "newline_normalization", "strip_nonempty_lines"],
            "repair_strategy": "if parser candidates emit non-UTF8 source or mishandle bytes, normalize text/bytes first and return a literal list of decoded lines",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_parse_encoding_kv_pairs",
            "prompt": "Parse key-value pairs from mixed separators into a dictionary, lowercasing keys and preserving string values.",
            "entry": "private_parse_encoding_kv_pairs",
            "body": "if isinstance(data, bytes):\n    text = data.decode('utf-8', errors='ignore')\nelse:\n    text = '' if data is None else str(data)\nout = {}\nfor chunk in text.replace(';', '\\n').replace('&', '\\n').splitlines():\n    if '=' not in chunk:\n        continue\n    key, value = chunk.split('=', 1)\n    key = key.strip().lower()\n    value = value.strip()\n    if key:\n        out[key] = value\nreturn out",
            "cases": [("A=1; b = two\nignore", None, {"a": "1", "b": "two"}), (b"x=7&Y=8", None, {"x": "7", "y": "8"}), ("=bad\na=", None, {"a": ""}), (None, None, {})],
            "tags": ["parsing_encoding_v1", "parsing", "encoding", "dict", "key_value_parser", "return_shape"],
            "residual_concept": "parsing_encoding_v1",
            "concept_residual_label": "kv_separator_parser_contract",
            "return_shape": "dict",
            "type_family": "string_indexing",
            "argument_roles": {"data": "str|bytes|Any"},
            "required_constructs": ["branch", "loop", "locals", "index_or_string_ops", "collection_ops"],
            "skeleton_bias": ["bytes_decode_guard", "separator_normalization", "split_once_key_value", "dict_return_builder"],
            "repair_strategy": "if parsing candidates produce malformed source or list output, force split-once key/value logic with a literal dict return",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_parse_encoding_numeric_fields",
            "prompt": "Return signed integers embedded in text, bytes, or a sequence of fields.",
            "entry": "private_parse_encoding_numeric_fields",
            "body": "import re\nif isinstance(data, bytes):\n    text = data.decode('utf-8', errors='ignore')\nelif isinstance(data, (list, tuple)):\n    text = ' '.join('' if item is None else str(item) for item in data)\nelse:\n    text = '' if data is None else str(data)\nout = []\nfor token in re.findall(r'[-+]?\\d+', text):\n    try:\n        out.append(int(token))\n    except Exception:\n        pass\nreturn out",
            "cases": [("a=-2 b=+3 c", None, [-2, 3]), (["x9", None, b"-4"], None, [9, -4]), (b"bad\xff 10", None, [10]), (None, None, [])],
            "tags": ["parsing_encoding_v1", "parsing", "encoding", "numeric_text", "return_shape"],
            "residual_concept": "parsing_encoding_v1",
            "concept_residual_label": "numeric_text_encoding_parser",
            "return_shape": "list",
            "type_family": "string_indexing",
            "argument_roles": {"data": "str|bytes|sequence[Any]"},
            "required_constructs": ["branch", "loop", "locals", "index_or_string_ops", "type_and_return_shape"],
            "skeleton_bias": ["bytes_decode_guard", "sequence_join", "regex_signed_int_scan", "list_return_builder"],
            "repair_strategy": "if signed-number parsing fails, normalize all visible input families to text before the regex/token loop",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
        {
            "category": "private_parse_encoding_safe_identifier",
            "prompt": "Return a safe lowercase identifier from text or bytes, replacing non-alphanumeric runs with underscores.",
            "entry": "private_parse_encoding_safe_identifier",
            "body": "if isinstance(data, bytes):\n    text = data.decode('utf-8', errors='ignore')\nelse:\n    text = '' if data is None else str(data)\nout = []\nlast_us = False\nfor ch in text.strip().lower():\n    if ch.isalnum():\n        out.append(ch)\n        last_us = False\n    elif not last_us:\n        out.append('_')\n        last_us = True\nresult = ''.join(out).strip('_')\nif not result or result[0].isdigit():\n    result = '_' + result\nreturn result",
            "cases": [("Hello, World!", None, "hello_world"), (b"9 lives\xff", None, "_9_lives"), ("---", None, "_"), (None, None, "_")],
            "tags": ["parsing_encoding_v1", "parsing", "encoding", "identifier", "return_shape"],
            "residual_concept": "parsing_encoding_v1",
            "concept_residual_label": "safe_identifier_encoding_contract",
            "return_shape": "str",
            "type_family": "string_indexing",
            "argument_roles": {"data": "str|bytes|Any"},
            "required_constructs": ["branch", "loop", "locals", "index_or_string_ops", "return_shape"],
            "skeleton_bias": ["bytes_decode_guard", "character_loop", "underscore_run_collapse", "identifier_prefix_guard"],
            "repair_strategy": "if parser repair emits non-UTF8 or invalid identifiers, force character-level normalization with a final prefix guard",
            "guardrail_expectations": {"requires_loop": True, "requires_branch": True, "requires_locals": True, "min_assertions": 4},
        },
    ]
