"""Static high-transfer curriculum concept catalog.

The scheduler owns dynamic routing and gate state. This module owns the large
static command catalog so AI maintenance can change curriculum entries without
having to work inside the orchestration hot path.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

@dataclass(frozen=True)
class CurriculumCatalogContext:
    root: Path
    balanced_edge_contract_concept: str
    balanced_edge_contract_closure_concept: str
    balanced_edge_contract_train_jsonl: Path
    balanced_edge_contract_pressure_report: Path
    edge_case_full_body_concept: str
    edge_case_full_body_closure_concept: str
    edge_case_full_body_train_jsonl: Path
    edge_case_full_body_pressure_report: Path
    edge_contract_v2_concept: str
    edge_contract_v2_closure_concept: str
    edge_contract_v2_train_jsonl: Path
    edge_contract_v2_pressure_report: Path
    candidate_floor_v2_concept: str
    candidate_floor_v2_closure_concept: str
    candidate_floor_v2_train_jsonl: Path
    candidate_floor_v2_pressure_report: Path
    residual_edge_case_contract_concept: str
    residual_edge_case_contract_train_jsonl: Path
    residual_edge_case_contract_pressure_report: Path
    conversation_large_case_target: int
    conversation_hard_case_target: int
    conversation_hard_v2_case_target: int
    conversation_hard_v3_case_target: int
    conversation_hard_v4_case_target: int


def build_base_concepts(ctx: CurriculumCatalogContext) -> list[dict[str, Any]]:
    ROOT = ctx.root
    BALANCED_EDGE_CONTRACT_CONCEPT = ctx.balanced_edge_contract_concept
    BALANCED_EDGE_CONTRACT_CLOSURE_CONCEPT = ctx.balanced_edge_contract_closure_concept
    BALANCED_EDGE_CONTRACT_TRAIN_JSONL = ctx.balanced_edge_contract_train_jsonl
    BALANCED_EDGE_CONTRACT_PRESSURE_REPORT = ctx.balanced_edge_contract_pressure_report
    EDGE_CASE_FULL_BODY_CONCEPT = ctx.edge_case_full_body_concept
    EDGE_CASE_FULL_BODY_CLOSURE_CONCEPT = ctx.edge_case_full_body_closure_concept
    EDGE_CASE_FULL_BODY_TRAIN_JSONL = ctx.edge_case_full_body_train_jsonl
    EDGE_CASE_FULL_BODY_PRESSURE_REPORT = ctx.edge_case_full_body_pressure_report
    EDGE_CONTRACT_V2_CONCEPT = ctx.edge_contract_v2_concept
    EDGE_CONTRACT_V2_CLOSURE_CONCEPT = ctx.edge_contract_v2_closure_concept
    EDGE_CONTRACT_V2_TRAIN_JSONL = ctx.edge_contract_v2_train_jsonl
    EDGE_CONTRACT_V2_PRESSURE_REPORT = ctx.edge_contract_v2_pressure_report
    CANDIDATE_FLOOR_V2_CONCEPT = ctx.candidate_floor_v2_concept
    CANDIDATE_FLOOR_V2_CLOSURE_CONCEPT = ctx.candidate_floor_v2_closure_concept
    CANDIDATE_FLOOR_V2_TRAIN_JSONL = ctx.candidate_floor_v2_train_jsonl
    CANDIDATE_FLOOR_V2_PRESSURE_REPORT = ctx.candidate_floor_v2_pressure_report
    RESIDUAL_EDGE_CASE_CONTRACT_CONCEPT = ctx.residual_edge_case_contract_concept
    RESIDUAL_EDGE_CASE_CONTRACT_TRAIN_JSONL = ctx.residual_edge_case_contract_train_jsonl
    RESIDUAL_EDGE_CASE_CONTRACT_PRESSURE_REPORT = ctx.residual_edge_case_contract_pressure_report
    CONVERSATION_LARGE_CASE_TARGET = ctx.conversation_large_case_target
    CONVERSATION_HARD_CASE_TARGET = ctx.conversation_hard_case_target
    CONVERSATION_HARD_V2_CASE_TARGET = ctx.conversation_hard_v2_case_target
    CONVERSATION_HARD_V3_CASE_TARGET = ctx.conversation_hard_v3_case_target
    CONVERSATION_HARD_V4_CASE_TARGET = ctx.conversation_hard_v4_case_target

    return [
        {
            "concept": "type_contract_diagnostic",
            "priority": "critical",
            "private_pressure": "infer private return-shape, visible-argument, type-family, branch/loop/local, and skeleton contracts, then write Decoder V2 feedback rows",
            "donors": ["private_type_contract_rows", "source_mbpp", "source_evalplus"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/type_contract_diagnostic.py",
                "--max-rows",
                "960",
            ],
        },
        {
            "concept": "type_and_return_shape",
            "priority": "critical",
            "private_pressure": "vary signatures, nested containers, scalar/list/string/int returns, conversion boundaries, and None/empty cases",
            "donors": ["source_mbpp", "source_evalplus"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": ["python", "scripts/code_residual_curriculum.py", "--max-rows", "960"],
        },
        {
            "concept": "typed_interface_skeleton",
            "priority": "critical",
            "private_pressure": "source-agnostic tasks that couple visible signature use, type-family routing, local branch/loop skeletons, and exact return-shape contracts",
            "donors": ["private_type_and_return_shape", "private_admissibility_and_interface"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--max-rows",
                "960",
                "--concept-focus",
                "typed_interface_skeleton",
            ],
        },
        {
            "concept": "typed_interface_private_closure",
            "priority": "critical",
            "private_pressure": "train and evaluate Code LM on the fresh private typed-interface skeleton rows with public calibration skipped",
            "donors": ["private_typed_interface_skeleton"],
            "receivers": ["private_code_lm_closure", "private_sts_repair"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--high-transfer-private-train-jsonl",
                "D:/ProjectTheseus/training_data/high_transfer/private_train/typed_interface_skeleton_residual_code_lm_tasks.jsonl",
            ],
        },
        {
            "concept": "decoder_plan_ir_code_lm_adapter",
            "priority": "critical",
            "private_pressure": "convert private Decoder Plan IR skeleton/repair pressure into Code LM rows before the next private closure",
            "donors": ["private_decoder_plan_ir", "private_code_lm_curriculum", "public_residual_categories_only"],
            "receivers": ["private_code_lm_closure", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/decoder_plan_ir_code_lm_adapter.py",
            ],
        },
        {
            "concept": "private_pressure_private_closure",
            "priority": "critical",
            "private_pressure": "consume the fresh source-agnostic private type/interface/edge/algorithmic rows in a private-only Code LM closure before any public receiver calibration",
            "donors": [
                "private_type_and_return_shape",
                "private_admissibility_and_interface",
                "private_edge_conditions",
                "private_edge_contract_4card",
                "private_balanced_edge_contract_4card_v2",
                "private_edge_case_full_body",
                "private_algorithmic_planning",
                "private_type_contract_decoder_feedback",
                "private_execution_shaped_programs",
                "private_residual_targeted_edge_case_contract_v1",
                "private_decoder_plan_ir_code_lm",
            ],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_train_once_fanout.py",
                "--private-only",
                "--execute",
                "--slug",
                "frontier_private_transfer_private_only_train_once_v1",
                "--private-count",
                "480",
                "--epochs",
                "4",
                "--candidates-per-task",
                "8",
                "--max-high-transfer-private-train",
                "6400",
                "--max-rust-work-steps",
                "4000000",
                "--rust-timeout-seconds",
                "7200",
                "--fanout-timeout-seconds",
                "21600",
                "--out",
                "reports/code_lm_train_once_fanout.json",
                "--markdown-out",
                "reports/code_lm_train_once_fanout.md",
            ],
        },
        {
            "concept": "edge_conditions",
            "priority": "high",
            "private_pressure": "empty/singleton inputs, final-element exceptions, leading zeros, punctuation, negative values, and boundary thresholds",
            "donors": ["source_human_eval", "source_mbpp"],
            "receivers": ["source_evalplus", "source_mbpp", "source_livecodebench"],
            "command": ["python", "scripts/code_residual_curriculum.py", "--max-rows", "960"],
        },
        {
            "concept": "edge_contract_4card",
            "priority": "critical",
            "private_pressure": "benchmark-neutral 4-card residual pressure for explicit boundary handling, input admissibility, return-shape contracts, and branch/loop local skeletons",
            "donors": ["teacher_residual_cluster", "private_edge_conditions", "private_type_and_return_shape"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--max-rows",
                "960",
                "--concept-focus",
                "edge_contract_4card",
            ],
        },
        {
            "concept": "edge_contract_private_closure",
            "priority": "critical",
            "private_pressure": "train and evaluate Code LM on the benchmark-neutral edge-contract residual rows with public calibration skipped",
            "donors": ["private_edge_contract_4card"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--high-transfer-private-train-jsonl",
                "D:/ProjectTheseus/training_data/high_transfer/private_train/edge_contract_4card_residual_code_lm_tasks.jsonl",
            ],
        },
        {
            "concept": BALANCED_EDGE_CONTRACT_CONCEPT,
            "priority": "critical",
            "private_pressure": "teacher-requested private-only balanced edge contract curriculum: typed interface skeletons, edge tests, admissibility, return-shape feedback, branch/loop/local skeletons, and algorithm planning with execution-shaped rows capped",
            "donors": ["teacher_architecture_wall", "private_type_and_return_shape", "private_edge_conditions", "private_admissibility_and_interface"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--max-rows",
                "960",
                "--concept-focus",
                BALANCED_EDGE_CONTRACT_CONCEPT,
                "--private-out",
                str(BALANCED_EDGE_CONTRACT_TRAIN_JSONL).replace("\\", "/"),
                "--out",
                str(BALANCED_EDGE_CONTRACT_PRESSURE_REPORT.relative_to(ROOT)).replace("\\", "/"),
                "--markdown-out",
                "reports/high_transfer_edge_contract_balanced_4card_private_curriculum_v2_code_residual_curriculum.md",
            ],
        },
        {
            "concept": BALANCED_EDGE_CONTRACT_CLOSURE_CONCEPT,
            "priority": "critical",
            "private_pressure": "train/evaluate Code LM on the teacher-requested balanced private edge-contract file with public calibration skipped before any receiver rerun",
            "donors": ["private_balanced_edge_contract_4card_v2"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--high-transfer-private-train-jsonl",
                str(BALANCED_EDGE_CONTRACT_TRAIN_JSONL).replace("\\", "/"),
            ],
        },
        {
            "concept": EDGE_CASE_FULL_BODY_CONCEPT,
            "priority": "critical",
            "private_pressure": "teacher-requested private full-body edge-case curriculum: return-shape, boundary inputs, branch/loop/local state, and admissible interface contracts with normal plus edge assertions",
            "donors": ["teacher_architecture_wall", "private_edge_contract_4card", "private_type_and_return_shape"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--trace-in",
                "reports/real_code_benchmark_traces_edge_contract_4card_private_4card_seed31_32.jsonl",
                "--real-code-report",
                "reports/real_code_benchmark_graduation_edge_contract_4card_private_4card_seed31_32.json",
                "--max-rows",
                "960",
                "--concept-focus",
                EDGE_CASE_FULL_BODY_CONCEPT,
                "--private-out",
                str(EDGE_CASE_FULL_BODY_TRAIN_JSONL).replace("\\", "/"),
                "--out",
                str(EDGE_CASE_FULL_BODY_PRESSURE_REPORT.relative_to(ROOT)).replace("\\", "/"),
                "--markdown-out",
                "reports/high_transfer_edge_case_full_body_private_curriculum_v1_code_residual_curriculum.md",
            ],
        },
        {
            "concept": EDGE_CASE_FULL_BODY_CLOSURE_CONCEPT,
            "priority": "critical",
            "private_pressure": "train/evaluate Code LM on the teacher-requested full-body edge-case private shard with public calibration skipped; this is the held-out private gate before any receiver rerun",
            "donors": ["private_edge_case_full_body"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--high-transfer-private-train-jsonl",
                str(EDGE_CASE_FULL_BODY_TRAIN_JSONL).replace("\\", "/"),
            ],
        },
        {
            "concept": EDGE_CONTRACT_V2_CONCEPT,
            "priority": "critical",
            "private_pressure": "teacher-requested edge-contract v2 private residual curriculum: interface contracts, return-shape correctness, empty/singleton/boundary cases, branch/loop termination, local state updates, type-family handling, and generation-plan decoder contracts",
            "donors": ["teacher_architecture_wall", "private_edge_case_full_body", "private_admissibility_and_interface", "private_type_and_return_shape"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--trace-in",
                "reports/real_code_benchmark_traces_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.jsonl",
                "--real-code-report",
                "reports/real_code_benchmark_graduation_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.json",
                "--max-rows",
                "960",
                "--concept-focus",
                EDGE_CONTRACT_V2_CONCEPT,
                "--private-out",
                str(EDGE_CONTRACT_V2_TRAIN_JSONL).replace("\\", "/"),
                "--out",
                str(EDGE_CONTRACT_V2_PRESSURE_REPORT.relative_to(ROOT)).replace("\\", "/"),
                "--markdown-out",
                "reports/high_transfer_edge_contract_v2_private_residual_curriculum_code_residual_curriculum.md",
            ],
        },
        {
            "concept": EDGE_CONTRACT_V2_CLOSURE_CONCEPT,
            "priority": "critical",
            "private_pressure": "train/evaluate Code LM on edge-contract v2 rows with public calibration skipped, then run the v2 private verifier before any receiver rerun",
            "donors": ["private_edge_contract_v2"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--high-transfer-private-train-jsonl",
                str(EDGE_CONTRACT_V2_TRAIN_JSONL).replace("\\", "/"),
            ],
        },
        {
            "concept": CANDIDATE_FLOOR_V2_CONCEPT,
            "priority": "critical",
            "private_pressure": "private-only candidate floor pressure for no-admissible candidates, recursive/nested structures, two-argument interface fidelity, and list/string transform bodies before any public rerun",
            "donors": ["code_candidate_floor_diagnostic", "private_edge_contract_v2", "private_typed_interface_skeleton"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--trace-in",
                "reports/real_code_benchmark_traces_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.jsonl",
                "--real-code-report",
                "reports/real_code_benchmark_graduation_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.json",
                "--max-rows",
                "960",
                "--concept-focus",
                CANDIDATE_FLOOR_V2_CONCEPT,
                "--private-out",
                str(CANDIDATE_FLOOR_V2_TRAIN_JSONL).replace("\\", "/"),
                "--out",
                str(CANDIDATE_FLOOR_V2_PRESSURE_REPORT.relative_to(ROOT)).replace("\\", "/"),
                "--markdown-out",
                "reports/high_transfer_candidate_floor_v2_private_residual_curriculum_code_residual_curriculum.md",
            ],
        },
        {
            "concept": CANDIDATE_FLOOR_V2_CLOSURE_CONCEPT,
            "priority": "critical",
            "private_pressure": "train/evaluate Code LM on candidate-floor-v2 rows with public calibration skipped; this must precede the next decoder/private ablation gate",
            "donors": ["private_candidate_floor_v2"],
            "receivers": ["private_code_lm_closure", "private_sts_repair", "decoder_v2_private_gate"],
            "command": [
                "python",
                "scripts/code_lm_closure.py",
                "--skip-public-calibration",
                "--typed-edge-exec-receiver-v1",
                "--edge-obligation-decode-gate-v1",
                "--private-type-shape-receiver-veto-v1",
                "--high-transfer-private-train-jsonl",
                str(CANDIDATE_FLOOR_V2_TRAIN_JSONL).replace("\\", "/"),
            ],
        },
        {
            "concept": RESIDUAL_EDGE_CASE_CONTRACT_CONCEPT,
            "priority": "critical",
            "private_pressure": "teacher-requested residual-targeted private edge-case contract rows for bool misuse, recursive/nested syntax, list-tail replacement, sort-by-second, combinations, local state, and two-argument fidelity before any public rerun",
            "donors": ["teacher_architecture_wall", "private_candidate_floor_v2", "private_edge_contract_v2", "decoder_v2_private_ablation_gate_residuals"],
            "receivers": ["private_code_lm_closure", "decoder_v2_private_gate", "source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--trace-in",
                "reports/real_code_benchmark_traces_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.jsonl",
                "--real-code-report",
                "reports/real_code_benchmark_graduation_source_mbpp_source_evalplus_source_bigcodebench_source_livecodebench_seed14_32.json",
                "--max-rows",
                "384",
                "--concept-focus",
                RESIDUAL_EDGE_CASE_CONTRACT_CONCEPT,
                "--private-out",
                str(RESIDUAL_EDGE_CASE_CONTRACT_TRAIN_JSONL).replace("\\", "/"),
                "--out",
                str(RESIDUAL_EDGE_CASE_CONTRACT_PRESSURE_REPORT.relative_to(ROOT)).replace("\\", "/"),
                "--markdown-out",
                "reports/high_transfer_residual_targeted_private_edge_case_contract_v1_code_residual_curriculum.md",
            ],
        },
        {
            "concept": "decoder_v2_private_ablation_gate",
            "priority": "critical",
            "private_pressure": "private-only gate comparing baseline, contract-guided skeletons, and STS-conditioned skeletons before any public 4-card receiver calibration",
            "donors": ["private_code_lm_closure", "decoder_v2_contract_guided_skeleton"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/decoder_v2_private_ablation_gate.py",
                "--out",
                "reports/decoder_v2_private_ablation_gate.json",
                "--markdown-out",
                "reports/decoder_v2_private_ablation_gate.md",
            ],
        },
        {
            "concept": "private_type_shape_receiver_veto_ablation",
            "priority": "critical",
            "private_pressure": "teacher-requested private-only receiver-disabled vs receiver-enabled ablation over identical type/return-shape candidate pools",
            "donors": [
                "teacher_public_transfer_residual",
                "private_code_lm_candidates",
                "private_type_contract_rows",
                "private_decoder_plan_ir_code_lm",
            ],
            "receivers": [
                "decoder_v2_private_gate",
                "private_code_lm_closure",
                "source_mbpp",
                "source_evalplus",
                "source_bigcodebench",
                "source_livecodebench",
            ],
            "command": [
                "python",
                "scripts/private_type_shape_receiver_ablation.py",
                "--max-tasks",
                "192",
            ],
        },
        {
            "concept": "type_contract_four_card_calibration",
            "priority": "critical",
            "private_pressure": "consume private type-contract Decoder V2 feedback rows, then run same-seed 32-per-card receiver calibration across MBPP, EvalPlus, BigCodeBench, and LiveCodeBench",
            "donors": ["private_type_contract_decoder_feedback"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/broad_transfer_closure_runner.py",
                "--execute",
                "--cards",
                "source_mbpp,source_evalplus,source_bigcodebench,source_livecodebench",
                "--seed",
                "14",
                "--max-public-cases-per-card",
                "32",
                "--typed-edge-exec-receiver-v1",
                "--private-type-shape-receiver-veto-v1",
                "--score-existing-public-candidates",
                "--student-candidate-manifest",
                "reports/student_code_candidates_private_pressure_private.jsonl",
            ],
        },
        {
            "concept": "edge_exec_repair_four_card_calibration",
            "priority": "critical",
            "private_pressure": "verify edge_exec_repair_v1_private_first: bounded private edge-condition repair after Decoder V2 semantic planning, then same-seed 32-per-card receiver calibration",
            "donors": ["private_edge_conditions", "private_type_contract_decoder_feedback"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/broad_transfer_closure_runner.py",
                "--execute",
                "--cards",
                "source_mbpp,source_evalplus,source_bigcodebench,source_livecodebench",
                "--seed",
                "14",
                "--max-public-cases-per-card",
                "32",
                "--typed-edge-exec-receiver-v1",
                "--private-type-shape-receiver-veto-v1",
                "--score-existing-public-candidates",
                "--student-candidate-manifest",
                "reports/student_code_candidates_private_pressure_private.jsonl",
            ],
        },
        {
            "concept": "execution_shaped_programs",
            "priority": "critical",
            "private_pressure": "private BigCodeBench-like little-program pressure: file/path/string processing, CSV/archive/json/system-library calls, multi-step state, edge behavior, and return-shape contracts",
            "donors": ["private_execution_shaped_programs", "source_bigcodebench_residual_categories_only"],
            "receivers": ["source_bigcodebench", "source_livecodebench", "source_mbpp", "source_evalplus"],
            "command": [
                "python",
                "scripts/code_residual_curriculum.py",
                "--max-rows",
                "960",
                "--concept-focus",
                "execution_shaped_programs",
            ],
        },
        {
            "concept": "execution_shape_private_ablation",
            "priority": "critical",
            "private_pressure": "same-seed private held-out execution-shaped ablation comparing semantic_plan_v2, edge_exec_repair_v1, and execution_shape_skeleton_decoder_private_v1 before public calibration",
            "donors": ["private_execution_shaped_programs", "execution_shape_skeleton_decoder_private_v1"],
            "receivers": ["private_execution_shape_heldout", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/execution_shape_private_ablation.py",
                "--seed",
                "14",
                "--train-rows",
                "320",
                "--eval-rows",
                "64",
            ],
        },
        {
            "concept": "execution_shaped_four_card_calibration",
            "priority": "critical",
            "private_pressure": "consume private execution-shaped Decoder V2 pressure, then run same-seed 32-per-card receiver calibration to test whether BigCodeBench moves off zero without cross-card regressions",
            "donors": ["private_execution_shaped_programs", "private_type_contract_decoder_feedback"],
            "receivers": ["source_bigcodebench", "source_livecodebench", "source_mbpp", "source_evalplus"],
            "command": [
                "python",
                "scripts/broad_transfer_closure_runner.py",
                "--execute",
                "--cards",
                "source_mbpp,source_evalplus,source_bigcodebench,source_livecodebench",
                "--seed",
                "14",
                "--max-public-cases-per-card",
                "32",
                "--typed-edge-exec-receiver-v1",
                "--private-type-shape-receiver-veto-v1",
                "--score-existing-public-candidates",
                "--student-candidate-manifest",
                "reports/student_code_candidates_private_pressure_private.jsonl",
            ],
        },
        {
            "concept": "admissibility_and_interface",
            "priority": "high",
            "private_pressure": "AST-constrained full-body skeletons, visible signature use, local variables, branch/loop interfaces, and return-shape checks",
            "donors": ["source_mbpp", "source_evalplus"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": ["python", "scripts/code_residual_curriculum.py", "--max-rows", "960"],
        },
        {
            "concept": "algorithmic_planning",
            "priority": "high",
            "private_pressure": "select recurrence, counting, sorting, search, dynamic state, and number-theory plans from prompt semantics",
            "donors": ["source_bigcodebench", "source_mbpp"],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": ["python", "scripts/code_residual_curriculum.py", "--max-rows", "960"],
        },
        {
            "concept": "private_pressure_four_card_recalibration",
            "priority": "critical",
            "private_pressure": "consume the freshly regenerated high-transfer private concept rows, then rerun same-seed 32-per-card receiver calibration before rotating away from code transfer",
            "donors": [
                "private_type_and_return_shape",
                "private_admissibility_and_interface",
                "private_edge_conditions",
                "private_edge_contract_4card",
                "private_edge_case_full_body",
                "private_algorithmic_planning",
            ],
            "receivers": ["source_mbpp", "source_evalplus", "source_bigcodebench", "source_livecodebench"],
            "command": [
                "python",
                "scripts/broad_transfer_closure_runner.py",
                "--execute",
                "--cards",
                "source_mbpp,source_evalplus,source_bigcodebench,source_livecodebench",
                "--seed",
                "14",
                "--max-public-cases-per-card",
                "32",
                "--typed-edge-exec-receiver-v1",
                "--private-type-shape-receiver-veto-v1",
                "--score-existing-public-candidates",
                "--student-candidate-manifest",
                "reports/student_code_candidates_private_pressure_private.jsonl",
            ],
        },
        {
            "concept": "open_conversation_pantry",
            "priority": "critical",
            "private_pressure": "license-allowlisted open conversational SFT/STS pressure rows, private-only provenance, no public benchmark proof",
            "donors": ["smol_smoltalk", "ultrachat_200k", "openassistant_oasst1"],
            "receivers": ["multi_turn_conversation", "dashboard_chat", "mobile_chat", "openai_compat_chat"],
            "command": ["python", "scripts/open_conversation_training_pantry.py"],
        },
        {
            "concept": "multi_turn_conversation",
            "priority": "critical",
            "private_pressure": "conversation memory, correction routing, personality-core adherence, task-state continuity, and follow-up resolution",
            "donors": ["private_multi_turn_conversation"],
            "receivers": ["dashboard_chat", "mobile_chat", "openai_compat_chat"],
            "command": [
                "python",
                "scripts/multi_turn_conversation_benchmark.py",
                "--suite-mode",
                "large",
                "--case-limit",
                str(CONVERSATION_LARGE_CASE_TARGET),
            ],
        },
        {
            "concept": "multi_turn_conversation_hard",
            "priority": "high",
            "private_pressure": "longer memory, interruptions, corrections, talk-while-working continuity, and personality stress tests",
            "donors": ["private_multi_turn_conversation", "personality_core"],
            "receivers": ["dashboard_chat", "mobile_chat", "openai_compat_chat", "operator_copilot"],
            "command": [
                "python",
                "scripts/multi_turn_conversation_benchmark.py",
                "--suite-mode",
                "hard",
                "--case-limit",
                str(CONVERSATION_HARD_CASE_TARGET),
                "--out",
                "reports/high_transfer_multi_turn_conversation_hard.json",
                "--markdown-out",
                "reports/high_transfer_multi_turn_conversation_hard.md",
                "--session-prefix",
                "hard_conversation_regression",
            ],
        },
        {
            "concept": "multi_turn_conversation_hard_v2",
            "priority": "high",
            "private_pressure": "harder conversation frontier with longer memory, interruptions, corrections, talk-while-working, evidence pressure, and personality stress at 128+ cases",
            "donors": ["private_multi_turn_conversation", "personality_core", "conversation_hard_regression"],
            "receivers": ["dashboard_chat", "mobile_chat", "openai_compat_chat", "operator_copilot"],
            "command": [
                "python",
                "scripts/multi_turn_conversation_benchmark.py",
                "--suite-mode",
                "hard_v2",
                "--case-limit",
                str(CONVERSATION_HARD_V2_CASE_TARGET),
                "--out",
                "reports/high_transfer_multi_turn_conversation_hard_v2.json",
                "--markdown-out",
                "reports/high_transfer_multi_turn_conversation_hard_v2.md",
                "--session-prefix",
                "hard_conversation_v2_frontier",
            ],
        },
        {
            "concept": "multi_turn_conversation_hard_v3",
            "priority": "high",
            "private_pressure": "product-grade conversation frontier with 256+ cases for long memory, corrections, interruptions, talk-while-working, hive control, permission boundaries, and A+ evidence discipline",
            "donors": ["private_multi_turn_conversation", "personality_core", "conversation_hard_v2_frontier"],
            "receivers": ["dashboard_chat", "mobile_chat", "openai_compat_chat", "operator_copilot", "hive_control_surface"],
            "command": [
                "python",
                "scripts/multi_turn_conversation_benchmark.py",
                "--suite-mode",
                "hard_v3",
                "--case-limit",
                str(CONVERSATION_HARD_V3_CASE_TARGET),
                "--out",
                "reports/high_transfer_multi_turn_conversation_hard_v3.json",
                "--markdown-out",
                "reports/high_transfer_multi_turn_conversation_hard_v3.md",
                "--session-prefix",
                "hard_conversation_v3_product_frontier",
            ],
        },
        {
            "concept": "multi_turn_conversation_hard_v4",
            "priority": "high",
            "private_pressure": "A+ conversation frontier with 384+ cases for conflicting evidence, live autonomy state, uncertainty discipline, correction persistence, and talk-while-working under pressure",
            "donors": ["private_multi_turn_conversation", "personality_core", "conversation_hard_v3_product_frontier"],
            "receivers": ["dashboard_chat", "mobile_chat", "openai_compat_chat", "operator_copilot", "hive_control_surface"],
            "command": [
                "python",
                "scripts/multi_turn_conversation_benchmark.py",
                "--suite-mode",
                "hard_v4",
                "--case-limit",
                str(CONVERSATION_HARD_V4_CASE_TARGET),
                "--out",
                "reports/high_transfer_multi_turn_conversation_hard_v4.json",
                "--markdown-out",
                "reports/high_transfer_multi_turn_conversation_hard_v4.md",
                "--session-prefix",
                "hard_conversation_v4_a_plus_frontier",
            ],
        },
        {
            "concept": "repo_repair",
            "priority": "high",
            "private_pressure": "repo snapshot, bug inference, patch, tests, residual label, repair trace, checkpoint update, and public calibration",
            "donors": ["private_repo_repair"],
            "receivers": ["source_bigcodebench", "source_livecodebench", "swe_style_private"],
            "command": ["python", "scripts/viea_repo_repair_learner.py"],
        },
        {
            "concept": "long_horizon_tool_use",
            "priority": "medium",
            "private_pressure": "local terminal/tool-use tasks for background lifecycle, checkpoints, resume, bounded retry, evidence routing, and tool rot detection",
            "donors": ["hive_work_board", "world_execution_jobs", "local_terminal_tool_use"],
            "receivers": ["vacation_mode", "repo_repair", "remote_control", "cloud_compute", "code_generation_arm"],
            "command": [
                "python",
                "scripts/long_horizon_tool_use_benchmark.py",
                "--out",
                "reports/high_transfer_long_horizon_tool_use.json",
                "--markdown-out",
                "reports/high_transfer_long_horizon_tool_use.md",
                "--trace-out",
                "D:/ProjectTheseus/training_data/tool_use/private_train/long_horizon_tool_use_traces.jsonl",
                "--sts-out",
                "D:/ProjectTheseus/training_data/tool_use/sts/long_horizon_tool_use_sts.jsonl",
                "--max-cases",
                "64",
            ],
        },
        {
            "concept": "board_game_rl",
            "priority": "medium",
            "private_pressure": "local chess and Go self-play with legal-action masking, tactical gates, sparse reward, and Elo-style trend evidence",
            "donors": ["source_chess_rl", "source_go_rl", "local_self_play"],
            "receivers": ["rl_local", "long_horizon_tool_use", "planning_control"],
            "command": [
                "python",
                "scripts/board_game_rl_benchmark.py",
                "--games",
                "chess,go",
                "--seed",
                "14",
                "--chess-games",
                "24",
                "--go-games",
                "24",
                "--go-board-size",
                "5",
                "--learned-policy-out",
                "reports/board_game_learned_policy.json",
            ],
        },
        {
            "concept": "pufferlib4_rl",
            "priority": "medium",
            "private_pressure": "PufferLib 4/Ocean fast RL readiness, legal-asset-gated Atari, rollout contracts, sparse reward, reset/step interfaces, and RL-to-code STS capsules",
            "donors": ["pufferlib4_ocean", "local_synthetic_rl", "board_game_rl"],
            "receivers": ["cross_domain_sts_capsules", "long_horizon_tool_use", "repo_repair", "code_generation_arm"],
            "command": [
                "python",
                "scripts/pufferlib4_rl_lane.py",
                "--probe",
                "--out",
                "reports/pufferlib4_rl_lane.json",
                "--markdown-out",
                "reports/pufferlib4_rl_lane.md",
                "--capsules-out",
                "D:/ProjectTheseus/training_data/rl/pufferlib4/pufferlib4_rl_sts_capsules.jsonl",
            ],
        },
        {
            "concept": "cross_domain_sts_capsules",
            "priority": "high",
            "private_pressure": "convert conversation, board-game RL, PufferLib/Ocean, long-horizon tool-use, and repo-repair evidence into metadata-only STS skill capsules for transfer across arms",
            "donors": ["conversation_hard", "board_game_rl", "pufferlib4_rl", "long_horizon_tool_use", "repo_repair"],
            "receivers": ["symliquid_state_engine", "octopus_router", "code_generation_arm", "repo_repair_arm", "conversation_arm"],
            "command": [
                "python",
                "scripts/cross_domain_sts_capsules.py",
                "--out",
                "reports/cross_domain_sts_capsules.json",
                "--markdown-out",
                "reports/cross_domain_sts_capsules.md",
                "--capsules-out",
                "data/training_sources/cross_domain_sts_capsules.jsonl",
                "--sts-out",
                "D:/ProjectTheseus/training_data/cross_domain_sts/cross_domain_sts_streams.jsonl",
            ],
        },
    ]
