#!/usr/bin/env python3
"""Token-decoder rendering and deterministic body construction helpers.

This module owns body-token decoding, strict-action rendering, semantic-slot
rendering, and deterministic body renderer utilities for neural seed token
decoders. These renderers are diagnostic/tooling surfaces only; they do not
inspect tests/solutions, use public benchmark payloads, call a teacher, or grant
learned-code-generation credit.
"""

from __future__ import annotations

import ast
import base64
import io
import math
import textwrap
from typing import Any

from neural_seed_code_proposer_comparator import get_path, render_private_function
import semantic_ir


PLAN_PREFIX_BODY_TARGET_MODE = "plan_prefix_body_tokens_v1"
PLAN_SEMANTIC_SLOTS_BODY_TARGET_MODE = "plan_semantic_slots_body_tokens_v1"
PLAN_SEMANTIC_STMT_SLOTS_BODY_TARGET_MODE = "plan_semantic_stmt_slots_body_tokens_v1"
PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE = "plan_semantic_stmt_expression_transition_body_tokens_v1"
PLAN_BODY_START_TOKEN = "SLOT:BODY_START"
BODY_EXPRESSION_TRACE_PREFIX = "TRACE:EXPR_"
TYPED_SEMANTIC_IR_TARGET_MODE = semantic_ir.TARGET_MODE


def task_family(task: dict[str, Any]) -> str:
    return str(
        get_path(task, ["decoder_contract", "type_family"], "")
        or task.get("targeted_private_residual_family_v3")
        or task.get("residual_concept")
        or "unknown"
    )


def learned_plan_prefix_target_mode(target_mode: str) -> bool:
    return str(target_mode or "") in {
        PLAN_PREFIX_BODY_TARGET_MODE,
        PLAN_SEMANTIC_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE,
    }


def learned_plan_semantic_slots_body_target_mode(target_mode: str) -> bool:
    return str(target_mode or "") in {
        PLAN_SEMANTIC_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE,
    }


def learned_plan_statement_slots_body_target_mode(target_mode: str) -> bool:
    return str(target_mode or "") in {
        PLAN_SEMANTIC_STMT_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE,
    }


def learned_plan_expression_transition_body_target_mode(target_mode: str) -> bool:
    return str(target_mode or "") == PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE


def body_like_target_mode(target_mode: str) -> bool:
    return str(target_mode or "") in {
        "body_tokens",
        PLAN_PREFIX_BODY_TARGET_MODE,
        PLAN_SEMANTIC_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_SLOTS_BODY_TARGET_MODE,
        PLAN_SEMANTIC_STMT_EXPR_TRANSITION_BODY_TARGET_MODE,
    }


def body_expression_trace_token(tok: str) -> bool:
    return str(tok or "").startswith(BODY_EXPRESSION_TRACE_PREFIX)


def split_learned_plan_prefix_tokens(tokens: list[str]) -> tuple[list[str], dict[str, Any]]:
    prefix_tokens: list[str] = []
    body: list[str] = []
    body_started = False
    for tok in tokens:
        if tok in {"<pad>", "<bos>", "<unk>"}:
            continue
        if tok == "<eos>":
            break
        if not body_started and tok == PLAN_BODY_START_TOKEN:
            prefix_tokens.append(tok)
            body_started = True
            continue
        if not body_started and tok.startswith("SLOT:PLAN_"):
            prefix_tokens.append(tok)
            continue
        if not body_started and tok.startswith("SLOT:"):
            prefix_tokens.append(tok)
            continue
        body_started = True
        body.append(tok)
    plan_tokens = [tok for tok in prefix_tokens if tok.startswith("SLOT:PLAN_")]
    return body, {
        "learned_plan_prefix_used": bool(prefix_tokens),
        "learned_plan_prefix_complete": PLAN_BODY_START_TOKEN in prefix_tokens,
        "learned_plan_prefix_tokens": prefix_tokens,
        "predicted_plan_token": plan_tokens[0] if plan_tokens else "",
        "predicted_plan": plan_tokens[0].removeprefix("SLOT:PLAN_") if plan_tokens else "",
        "score_semantics": (
            "Learned plan-prefix tokens are generated by the same decoder from visible source text "
            "and are stripped before body compilation. They are not rendered into code and grant no "
            "template, tool, fallback, or structural-adapter generation credit."
        ),
    }


def strict_action_tokens(body: str) -> list[str]:
    """Encode a private solution body as explicit statement/action tokens.

    This is a diagnostic target, not promotion-grade learned code generation.
    It lets the model learn a stricter program-shape sequence while a fixed
    renderer reconstructs Python syntax from predicted actions. The renderer
    never reads eval tests/solutions and never inserts a fallback return.
    """

    try:
        parsed = ast.parse(render_synthetic_function(body))
        function = next((node for node in parsed.body if isinstance(node, ast.FunctionDef)), None)
    except SyntaxError:
        function = None
    if function is None:
        return ["ACT:INVALID_BODY"]
    tokens: list[str] = []
    for stmt in function.body:
        tokens.extend(strict_action_tokens_for_stmt(stmt))
    return tokens or ["ACT:PASS"]


def strict_action_tokens_for_stmt(stmt: ast.stmt) -> list[str]:
    if isinstance(stmt, ast.Import):
        names = ",".join(alias.name for alias in stmt.names if safe_module_name(alias.name))
        return ["ACT:IMPORT", encoded_field_token("EXPR", names or "math")]
    if isinstance(stmt, ast.ImportFrom):
        module = stmt.module or ""
        names = ",".join(alias.name for alias in stmt.names if alias.name.isidentifier())
        if not safe_module_name(module):
            module = "math"
        return ["ACT:FROM_IMPORT", encoded_field_token("EXPR", f"{module}:{names}")]
    if isinstance(stmt, ast.Assign):
        target = assign_target_name(stmt.targets[0] if stmt.targets else None)
        return ["ACT:ASSIGN", f"TARGET:{target}", encoded_expr_token(stmt.value)]
    if isinstance(stmt, ast.AnnAssign):
        return ["ACT:ASSIGN", f"TARGET:{assign_target_name(stmt.target)}", encoded_expr_token(stmt.value)]
    if isinstance(stmt, ast.AugAssign):
        return [
            "ACT:AUGASSIGN",
            f"TARGET:{assign_target_name(stmt.target)}",
            f"OP:{augassign_op(stmt.op)}",
            encoded_expr_token(stmt.value),
        ]
    if isinstance(stmt, ast.For):
        tokens = [
            "ACT:FOR",
            f"TARGET:{assign_target_name(stmt.target)}",
            encoded_field_token("ITER", ast.unparse(stmt.iter)),
            "ACT:BLOCK_BEGIN",
        ]
        for child in stmt.body:
            tokens.extend(strict_action_tokens_for_stmt(child))
        tokens.append("ACT:BLOCK_END")
        if stmt.orelse:
            tokens.extend(["ACT:ELSE", "ACT:BLOCK_BEGIN"])
            for child in stmt.orelse:
                tokens.extend(strict_action_tokens_for_stmt(child))
            tokens.append("ACT:BLOCK_END")
        return tokens
    if isinstance(stmt, ast.While):
        tokens = ["ACT:WHILE", encoded_field_token("TEST", ast.unparse(stmt.test)), "ACT:BLOCK_BEGIN"]
        for child in stmt.body:
            tokens.extend(strict_action_tokens_for_stmt(child))
        tokens.append("ACT:BLOCK_END")
        return tokens
    if isinstance(stmt, ast.If):
        tokens = ["ACT:IF", encoded_field_token("TEST", ast.unparse(stmt.test)), "ACT:BLOCK_BEGIN"]
        for child in stmt.body:
            tokens.extend(strict_action_tokens_for_stmt(child))
        tokens.append("ACT:BLOCK_END")
        if stmt.orelse:
            tokens.extend(["ACT:ELSE", "ACT:BLOCK_BEGIN"])
            for child in stmt.orelse:
                tokens.extend(strict_action_tokens_for_stmt(child))
            tokens.append("ACT:BLOCK_END")
        return tokens
    if isinstance(stmt, ast.Try):
        tokens = ["ACT:TRY", "ACT:BLOCK_BEGIN"]
        for child in stmt.body:
            tokens.extend(strict_action_tokens_for_stmt(child))
        tokens.append("ACT:BLOCK_END")
        for handler in stmt.handlers[:1]:
            tokens.extend(["ACT:EXCEPT", "ACT:BLOCK_BEGIN"])
            for child in handler.body:
                tokens.extend(strict_action_tokens_for_stmt(child))
            tokens.append("ACT:BLOCK_END")
        return tokens
    if isinstance(stmt, ast.Expr):
        return ["ACT:EXPR", encoded_expr_token(stmt.value)]
    if isinstance(stmt, ast.Return):
        expr = ast.Constant(value=None) if stmt.value is None else stmt.value
        return ["ACT:RETURN", encoded_expr_token(expr)]
    if isinstance(stmt, ast.Pass):
        return ["ACT:PASS"]
    if isinstance(stmt, ast.Break):
        return ["ACT:BREAK"]
    if isinstance(stmt, ast.Continue):
        return ["ACT:CONTINUE"]
    return ["ACT:EXPR", encoded_field_token("EXPR", "None")]


def assign_target_name(node: ast.AST | None) -> str:
    if isinstance(node, ast.Name) and node.id.isidentifier():
        return node.id
    if isinstance(node, ast.Tuple):
        names = [elt.id for elt in node.elts if isinstance(elt, ast.Name) and elt.id.isidentifier()]
        if names:
            return ", ".join(names)
    return "_tmp"


def augassign_op(node: ast.AST) -> str:
    table = {
        ast.Add: "+=",
        ast.Sub: "-=",
        ast.Mult: "*=",
        ast.Div: "/=",
        ast.FloorDiv: "//=",
        ast.Mod: "%=",
    }
    return table.get(type(node), "+=")


def encoded_expr_token(node: ast.AST | None) -> str:
    if node is None:
        return encoded_field_token("EXPR", "None")
    try:
        expr = ast.unparse(node)
    except Exception:
        expr = "None"
    return encoded_field_token("EXPR", expr)


def encoded_field_token(prefix: str, value: str) -> str:
    payload = base64.urlsafe_b64encode(str(value).encode("utf-8", errors="replace")).decode("ascii")
    return f"{prefix}:{payload}"


def decoded_field_token(tok: str, prefix: str) -> tuple[str, bool]:
    raw_prefix, _, payload = tok.partition(":")
    if raw_prefix != prefix or not payload:
        return "", False
    try:
        value = base64.urlsafe_b64decode(payload.encode("ascii")).decode("utf-8", errors="replace")
        return value, True
    except Exception:
        return "", False


def safe_module_name(value: str) -> bool:
    return bool(value) and all(part.isidentifier() for part in str(value).split("."))


def render_synthetic_function(body: str) -> str:
    lines = normalize_body_text(body).splitlines() or ["pass"]
    return "def _theseus_synthetic_body(data, other=None):\n" + "\n".join(f"    {line}" if line else "" for line in lines) + "\n"


def statement_skeleton_tokens(stmt: ast.stmt) -> list[str]:
    if isinstance(stmt, (ast.Import, ast.ImportFrom)):
        names = [alias.name for alias in getattr(stmt, "names", [])]
        return ["SKEL:IMPORT_MATH"] if "math" in names else ["SKEL:IMPORT"]
    if isinstance(stmt, ast.Assign):
        return [f"SKEL:ASSIGN_{value_shape(stmt.value).upper()}"]
    if isinstance(stmt, ast.AnnAssign):
        return [f"SKEL:ASSIGN_{value_shape(stmt.value).upper()}"]
    if isinstance(stmt, ast.AugAssign):
        return ["SKEL:ACCUMULATE"]
    if isinstance(stmt, ast.For):
        tokens = ["SKEL:LOOP_DATA" if iter_uses_data(stmt.iter) else "SKEL:LOOP_OTHER"]
        for child in stmt.body:
            tokens.extend(statement_skeleton_tokens(child))
        for child in stmt.orelse:
            tokens.extend(statement_skeleton_tokens(child))
        return tokens
    if isinstance(stmt, ast.While):
        tokens = ["SKEL:LOOP_WHILE"]
        for child in stmt.body:
            tokens.extend(statement_skeleton_tokens(child))
        return tokens
    if isinstance(stmt, ast.If):
        tokens = ["SKEL:BRANCH_GUARD"]
        for child in stmt.body:
            tokens.extend(statement_skeleton_tokens(child))
        for child in stmt.orelse:
            tokens.extend(statement_skeleton_tokens(child))
        return tokens
    if isinstance(stmt, ast.Try):
        tokens = ["SKEL:TRY_EXCEPT"]
        for child in stmt.body:
            tokens.extend(statement_skeleton_tokens(child))
        for handler in stmt.handlers:
            for child in handler.body:
                tokens.extend(statement_skeleton_tokens(child))
        return tokens
    if isinstance(stmt, ast.Expr):
        if isinstance(stmt.value, ast.Call):
            return ["SKEL:CALL_APPEND" if call_name(stmt.value).endswith(".append") else "SKEL:CALL"]
        return ["SKEL:EXPR"]
    if isinstance(stmt, ast.Continue):
        return ["SKEL:CONTINUE"]
    if isinstance(stmt, ast.Break):
        return ["SKEL:BREAK"]
    if isinstance(stmt, ast.Return):
        return [f"SKEL:RETURN_{return_shape_from_expr(stmt.value).upper()}"]
    return [f"SKEL:STMT_{stmt.__class__.__name__.upper()}"]


def iter_uses_data(node: ast.AST) -> bool:
    return isinstance(node, ast.Name) and node.id == "data"


def value_shape(node: ast.AST | None) -> str:
    if node is None:
        return "unknown"
    if isinstance(node, ast.Name):
        name = node.id.lower()
        if name in {"data", "rows", "items", "values", "parts", "out", "result"}:
            return "list"
        if name in {"other", "query", "record", "row", "config", "request"}:
            return "mapping_or_input"
        if name in {"total", "count", "best", "score", "idx", "index"}:
            return "number"
        if name in {"ok", "valid", "flag", "passed"}:
            return "bool"
    if isinstance(node, ast.List):
        return "list"
    if isinstance(node, ast.Dict):
        return "dict"
    if isinstance(node, ast.Set):
        return "set"
    if isinstance(node, ast.Tuple):
        return "tuple"
    if isinstance(node, ast.Constant):
        if isinstance(node.value, bool):
            return "bool"
        if isinstance(node.value, (int, float)):
            return "number"
        if isinstance(node.value, str):
            return "str"
        if node.value is None:
            return "none"
    if isinstance(node, ast.Call):
        name = call_name(node)
        if name in {"list", "sorted"}:
            return "list"
        if name in {"tuple", "zip", "enumerate"}:
            return "tuple"
        if name == "dict":
            return "dict"
        if name == "set":
            return "set"
        if name in {"str", "''.join"} or name.endswith(".join"):
            return "str"
        if name in {"int", "float", "len", "sum", "max", "min"}:
            return "number"
        if name == "bool":
            return "bool"
        if name.endswith(".get"):
            return "lookup"
        if name.endswith(".split") or name.endswith(".splitlines"):
            return "list"
        if name.endswith(".keys") or name.endswith(".values") or name.endswith(".items"):
            return "view"
    if isinstance(node, ast.ListComp):
        return "list"
    if isinstance(node, ast.DictComp):
        return "dict"
    if isinstance(node, ast.SetComp):
        return "set"
    if isinstance(node, ast.Compare):
        return "bool"
    if isinstance(node, ast.BoolOp):
        return "bool"
    if isinstance(node, ast.IfExp):
        left = value_shape(node.body)
        right = value_shape(node.orelse)
        return left if left == right else "conditional"
    if isinstance(node, ast.UnaryOp):
        return value_shape(node.operand)
    if isinstance(node, ast.Subscript):
        return "item"
    if isinstance(node, ast.BinOp):
        if isinstance(node.op, ast.Add):
            left = value_shape(node.left)
            right = value_shape(node.right)
            if left == right and left in {"list", "tuple", "str"}:
                return left
        return "number"
    return "unknown"


def return_shape_from_expr(node: ast.AST | None) -> str:
    shape = value_shape(node)
    if shape != "unknown":
        return shape
    if isinstance(node, ast.Name):
        name = node.id.lower()
        if name in {"answer", "total", "count", "best"}:
            return "number"
    if isinstance(node, ast.Attribute):
        return "attribute"
    if isinstance(node, ast.Lambda):
        return "callable"
    return "unknown"


def call_name(node: ast.Call) -> str:
    func = node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        base = ""
        if isinstance(func.value, ast.Name):
            base = func.value.id
        elif isinstance(func.value, ast.Constant):
            base = repr(func.value.value)
        return f"{base}.{func.attr}" if base else func.attr
    return ""


def decode_body_tokens(tokens: list[str]) -> str:
    lines: list[str] = []
    current: list[str] = []
    indent = 0

    def flush() -> None:
        nonlocal current
        line = token_values_to_line(current).strip()
        current = []
        if line:
            lines.append(("    " * max(0, indent)) + line)

    for tok in tokens:
        if tok in {"<pad>", "<bos>", "<unk>"}:
            continue
        if tok == "<eos>":
            break
        if body_expression_trace_token(tok):
            continue
        kind, _, value = tok.partition(":")
        if kind == "NEWLINE":
            flush()
        elif kind == "INDENT":
            flush()
            indent += 1
        elif kind == "DEDENT":
            flush()
            indent = max(0, indent - 1)
        elif kind == "RAW":
            current.append(value or "None")
        else:
            current.append(value)
    flush()
    return "\n".join(lines).strip()


def decode_candidate_body_tokens(
    tokens: list[str],
    task: dict[str, Any],
    *,
    target_mode: str,
) -> tuple[str, dict[str, Any]]:
    if semantic_ir.semantic_ir_target_mode(target_mode):
        body, meta = semantic_ir.compile_body_tokens(tokens)
        meta["target_mode"] = target_mode
        meta["fallback_return_used"] = False
        meta["task_family"] = task_family(task)
        return body, meta
    if target_mode == "semantic_slots_v1":
        body, meta = render_semantic_slot_body(tokens, task)
        meta["target_mode"] = target_mode
        meta["fallback_return_used"] = False
        meta["task_family"] = task_family(task)
        return body, meta
    if target_mode == "statement_skeleton_v1":
        body, meta = render_statement_skeleton_body(tokens)
        meta["target_mode"] = target_mode
        meta["fallback_return_used"] = False
        meta["task_family"] = task_family(task)
        return body, meta
    if target_mode == "strict_action_tokens_v1":
        body, meta = render_strict_action_body(tokens)
        meta["target_mode"] = target_mode
        meta["fallback_return_used"] = False
        meta["task_family"] = task_family(task)
        return body, meta
    if learned_plan_prefix_target_mode(target_mode):
        body_token_stream, prefix_meta = split_learned_plan_prefix_tokens(tokens)
        return decode_body_tokens(body_token_stream), {
            "target_mode": target_mode,
            **prefix_meta,
            "rendered_from_statement_skeleton": False,
            "rendered_from_strict_actions": False,
            "rendered_from_semantic_slots": False,
            "fallback_return_used": False,
            "task_family": task_family(task),
        }
    return decode_body_tokens(tokens), {
        "target_mode": target_mode,
        "rendered_from_statement_skeleton": False,
        "rendered_from_strict_actions": False,
        "fallback_return_used": False,
        "task_family": task_family(task),
    }


def render_strict_action_body(tokens: list[str]) -> tuple[str, dict[str, Any]]:
    parser = StrictActionRenderer(tokens)
    lines = parser.parse_block(stop_at_block_end=False, indent=0)
    body = "\n".join(lines).strip()
    return body, {
        "rendered_from_strict_actions": True,
        "strict_action_token_count": parser.action_token_count,
        "unique_strict_action_tokens": sorted(parser.unique_actions),
        "strict_action_rendered_line_count": len([line for line in lines if line.strip()]),
        "strict_action_pass_inserted_count": parser.pass_inserted_count,
        "strict_action_invalid_expr_count": parser.invalid_expr_count,
        "strict_action_unknown_token_count": parser.unknown_token_count,
        "strict_action_renderer_policy": "syntax_reconstruction_no_fallback_return_v1",
        "uses_eval_tests_or_solutions": False,
        "uses_public_data": False,
    }


class StrictActionRenderer:
    def __init__(self, tokens: list[str]) -> None:
        self.tokens = [tok for tok in tokens if tok not in {"<pad>", "<bos>", "<unk>"}]
        self.index = 0
        self.action_token_count = sum(1 for tok in self.tokens if tok.startswith("ACT:"))
        self.unique_actions = {tok for tok in self.tokens if tok.startswith("ACT:")}
        self.pass_inserted_count = 0
        self.invalid_expr_count = 0
        self.unknown_token_count = 0

    def parse_block(self, *, stop_at_block_end: bool, indent: int) -> list[str]:
        lines: list[str] = []
        while self.index < len(self.tokens):
            tok = self.peek()
            if tok == "<eos>":
                self.index += 1
                break
            if tok == "ACT:BLOCK_END":
                if stop_at_block_end:
                    self.index += 1
                    break
                self.index += 1
                continue
            rendered = self.parse_stmt(indent)
            if rendered:
                lines.extend(rendered)
        return lines

    def parse_stmt(self, indent: int) -> list[str]:
        tok = self.pop()
        prefix = "    " * max(0, indent)
        if tok == "ACT:ASSIGN":
            target = self.safe_target(self.take_prefixed("TARGET"))
            expr = self.safe_expr(self.take_prefixed("EXPR"))
            return [f"{prefix}{target} = {expr}"]
        if tok == "ACT:AUGASSIGN":
            target = self.safe_target(self.take_prefixed("TARGET"))
            op = self.safe_augassign(self.take_prefixed("OP") or "+=")
            expr = self.safe_expr(self.take_prefixed("EXPR"))
            return [f"{prefix}{target} {op} {expr}"]
        if tok == "ACT:FOR":
            target = self.safe_target(self.take_prefixed("TARGET") or "item")
            iterator = self.safe_expr(self.take_prefixed("ITER") or "data")
            body = self.take_child_block(indent + 1)
            lines = [f"{prefix}for {target} in {iterator}:"]
            lines.extend(body or self.inserted_pass(indent + 1))
            if self.peek() == "ACT:ELSE":
                self.pop()
                else_body = self.take_child_block(indent + 1)
                lines.append(f"{prefix}else:")
                lines.extend(else_body or self.inserted_pass(indent + 1))
            return lines
        if tok == "ACT:WHILE":
            test = self.safe_expr(self.take_prefixed("TEST") or "False")
            body = self.take_child_block(indent + 1)
            return [f"{prefix}while {test}:"] + (body or self.inserted_pass(indent + 1))
        if tok == "ACT:IF":
            test = self.safe_expr(self.take_prefixed("TEST") or "False")
            body = self.take_child_block(indent + 1)
            lines = [f"{prefix}if {test}:"]
            lines.extend(body or self.inserted_pass(indent + 1))
            if self.peek() == "ACT:ELSE":
                self.pop()
                else_body = self.take_child_block(indent + 1)
                lines.append(f"{prefix}else:")
                lines.extend(else_body or self.inserted_pass(indent + 1))
            return lines
        if tok == "ACT:TRY":
            body = self.take_child_block(indent + 1)
            lines = [f"{prefix}try:"]
            lines.extend(body or self.inserted_pass(indent + 1))
            if self.peek() == "ACT:EXCEPT":
                self.pop()
                handler = self.take_child_block(indent + 1)
                lines.append(f"{prefix}except Exception:")
                lines.extend(handler or self.inserted_pass(indent + 1))
            return lines
        if tok == "ACT:IMPORT":
            names = self.safe_import_names(self.take_prefixed("EXPR") or "math")
            return [f"{prefix}import {names}"]
        if tok == "ACT:FROM_IMPORT":
            module, names = self.safe_from_import(self.take_prefixed("EXPR") or "math:gcd")
            return [f"{prefix}from {module} import {names}"]
        if tok == "ACT:EXPR":
            return [f"{prefix}{self.safe_expr(self.take_prefixed('EXPR') or 'None')}"]
        if tok == "ACT:RETURN":
            return [f"{prefix}return {self.safe_expr(self.take_prefixed('EXPR') or 'None')}"]
        if tok == "ACT:PASS":
            return [f"{prefix}pass"]
        if tok == "ACT:BREAK":
            return [f"{prefix}break"]
        if tok == "ACT:CONTINUE":
            return [f"{prefix}continue"]
        self.unknown_token_count += 1
        return []

    def take_child_block(self, indent: int) -> list[str]:
        if self.peek() == "ACT:BLOCK_BEGIN":
            self.pop()
            return self.parse_block(stop_at_block_end=True, indent=indent)
        return []

    def inserted_pass(self, indent: int) -> list[str]:
        self.pass_inserted_count += 1
        return [f"{'    ' * max(0, indent)}pass"]

    def take_prefixed(self, prefix: str) -> str:
        tok = self.peek()
        if not tok or not tok.startswith(f"{prefix}:"):
            return ""
        self.pop()
        if prefix in {"EXPR", "ITER", "TEST"}:
            value, ok = decoded_field_token(tok, prefix)
            if ok:
                return value
            self.invalid_expr_count += 1
            return ""
        return tok.partition(":")[2]

    def safe_expr(self, expr: str) -> str:
        expr = str(expr or "None").strip() or "None"
        try:
            ast.parse(expr, mode="eval")
            return expr
        except SyntaxError:
            self.invalid_expr_count += 1
            return "None"

    def safe_target(self, target: str) -> str:
        target = str(target or "_tmp").strip()
        if all(part.strip().isidentifier() for part in target.split(",")):
            return ", ".join(part.strip() for part in target.split(","))
        return "_tmp"

    def safe_augassign(self, op: str) -> str:
        return op if op in {"+=", "-=", "*=", "/=", "//=", "%="} else "+="

    def safe_import_names(self, names: str) -> str:
        safe = [part for part in str(names).split(",") if safe_module_name(part.strip())]
        return ", ".join(safe or ["math"])

    def safe_from_import(self, value: str) -> tuple[str, str]:
        module, _, names = str(value).partition(":")
        module = module if safe_module_name(module) else "math"
        safe_names = [name for name in names.split(",") if name.strip().isidentifier()]
        return module, ", ".join(safe_names or ["gcd"])

    def peek(self) -> str:
        if self.index >= len(self.tokens):
            return ""
        return str(self.tokens[self.index])

    def pop(self) -> str:
        tok = self.peek()
        self.index += 1
        return tok


def render_semantic_slot_body(tokens: list[str], task: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    slot_tokens = []
    for tok in tokens:
        if tok == "<eos>":
            break
        if tok.startswith("SLOT:"):
            slot_tokens.append(tok)
    plan = decoded_semantic_plan(slot_tokens)
    body = render_supported_semantic_plan(plan)
    semantic_used = bool(body)
    if not body:
        body, skeleton_meta = render_statement_skeleton_body(tokens)
    else:
        skeleton_meta = {
            "rendered_from_statement_skeleton": False,
            "skeleton_token_count": sum(1 for tok in tokens if tok.startswith("SKEL:")),
            "unique_skeleton_tokens": sorted({tok for tok in tokens if tok.startswith("SKEL:")}),
            "predicted_loop": any(tok.startswith("SLOT:LOOP_SOURCE_") for tok in slot_tokens),
            "predicted_branch": any(tok.startswith("SLOT:GUARD_") for tok in slot_tokens),
            "predicted_try": "SLOT:GUARD_TRY_EXCEPT_CONTINUE" in slot_tokens,
            "predicted_append": any(tok.startswith("SLOT:UPDATE_APPEND") for tok in slot_tokens),
            "rendered_line_count": len(body.splitlines()),
        }
    return_shape = decoded_slot_value(slot_tokens, "SLOT:RETURN_SHAPE_") or decoded_return_shape(
        [tok for tok in tokens if tok.startswith("SKEL:")]
    )
    skeleton_meta.update(
        {
            "rendered_from_semantic_slots": semantic_used,
            "semantic_plan": plan,
            "semantic_plan_supported": semantic_used,
            "semantic_slot_count": len(slot_tokens),
            "unique_semantic_slots": sorted(set(slot_tokens)),
            "predicted_return_shape": return_shape or skeleton_meta.get("predicted_return_shape", ""),
            "predicted_loop_source": decoded_slot_value(slot_tokens, "SLOT:LOOP_SOURCE_"),
            "predicted_update_op": decoded_slot_value(slot_tokens, "SLOT:UPDATE_"),
            "predicted_guard_intent": decoded_slot_value(slot_tokens, "SLOT:GUARD_"),
            "predicted_finalizer": decoded_slot_value(slot_tokens, "SLOT:FINALIZER_"),
            "semantic_plan_fallback_used": False,
        }
    )
    return body, skeleton_meta


def decoded_semantic_plan(slot_tokens: list[str]) -> str:
    for tok in slot_tokens:
        if tok.startswith("SLOT:PLAN_"):
            return tok.removeprefix("SLOT:PLAN_")
    return ""


def decoded_slot_value(slot_tokens: list[str], prefix: str) -> str:
    for tok in slot_tokens:
        if tok.startswith(prefix):
            return tok.removeprefix(prefix).lower()
    return ""


def render_supported_semantic_plan(plan: str) -> str:
    renderers = {
        "SAFE_HEAD_DEFAULT": semantic_body_safe_head_default,
        "GROUP_RECORDS_BY_FIELD": semantic_body_group_records_by_field,
        "PROJECT_TABLE_COLUMNS": semantic_body_project_table_columns,
        "GCD_POSITIVE": semantic_body_gcd_positive,
        "NORMALIZE_FILTER_SORT_UNIQUE": semantic_body_normalize_filter_sort_unique,
        "WINDOWED_DELTAS": semantic_body_windowed_deltas,
        "BALANCED_BRACKETS": semantic_body_balanced_brackets,
        "STDIN_NUMERIC_PARSE": semantic_body_stdin_numeric_parse,
        "STDIN_PAIR_SUMS": semantic_body_stdin_pair_sums,
        "GRAPH_COMPONENTS": semantic_body_graph_components,
        "SHORTEST_HOPS": semantic_body_shortest_hops,
        "MAX_NON_ADJACENT_SUM": semantic_body_max_non_adjacent_sum,
        "LCS_LENGTH": semantic_body_lcs_length,
        "MERGE_INTERVALS": semantic_body_merge_intervals,
        "INTERVAL_COVERAGE": semantic_body_interval_coverage,
        "LONGEST_EVEN_RUN": semantic_body_longest_even_run,
        "RLE_ENCODE": semantic_body_rle_encode,
        "THRESHOLD_LABELS": semantic_body_threshold_labels,
        "TOP_K_FREQUENT": semantic_body_top_k_frequent,
        "MEDIA_PREVIEW_INDEX": semantic_body_media_preview_index,
        "ROOM_CAPABILITY_SUMMARY": semantic_body_room_capability_summary,
        "MEMORY_LATEST_BY_PROJECT": semantic_body_memory_latest_by_project,
        "MEMORY_OPEN_ACTION_ROLLUP": semantic_body_memory_open_action_rollup,
        "STORAGE_QUOTA_SELECT": semantic_body_storage_quota_select,
        "STORAGE_SYNC_PLAN": semantic_body_storage_sync_plan,
        "DEVICE_ROUTE_WORKER": semantic_body_device_route_worker,
        "VOICE_OUTPUT_ROUTE": semantic_body_voice_output_route,
        "PLAN_NEXT_UNBLOCKED": semantic_body_plan_next_unblocked,
        "PLAN_PROGRESS_DIGEST": semantic_body_plan_progress_digest,
        "LIST_APPEND": semantic_body_generic_list_append,
        "DICT_GROUP_APPEND": semantic_body_generic_dict_group_append,
        "SET_ADD": semantic_body_generic_set_add,
        "GENERIC_RETURN": semantic_body_generic_return,
    }
    renderer = renderers.get(plan)
    return renderer() if renderer else ""


def body_from_lines(lines: list[str]) -> str:
    return "\n".join(lines).strip()


def semantic_body_safe_head_default() -> str:
    return body_from_lines([
        "if isinstance(data, (list, tuple)) and data:",
        "    return data[0]",
        "return other",
    ])


def semantic_body_group_records_by_field() -> str:
    return body_from_lines([
        "out = {}",
        "for record in data or []:",
        "    if not isinstance(record, dict) or 'id' not in record:",
        "        continue",
        "    key = record.get(other)",
        "    if key is None:",
        "        continue",
        "    out.setdefault(str(key), []).append(record['id'])",
        "return out",
    ])


def semantic_body_project_table_columns() -> str:
    return body_from_lines([
        "columns = other or []",
        "out = []",
        "for row in data or []:",
        "    if not isinstance(row, dict):",
        "        continue",
        "    out.append({col: row.get(col) for col in columns})",
        "return out",
    ])


def semantic_body_gcd_positive() -> str:
    return body_from_lines([
        "import math",
        "answer = 0",
        "for value in data or []:",
        "    if isinstance(value, bool) or not isinstance(value, int):",
        "        continue",
        "    value = abs(value)",
        "    if value:",
        "        answer = math.gcd(answer, value)",
        "return answer",
    ])


def semantic_body_normalize_filter_sort_unique() -> str:
    return body_from_lines([
        "stop = {str(item).casefold() for item in (other or [])}",
        "out = set()",
        "for item in data or []:",
        "    text = str(item).strip().casefold()",
        "    if len(text) < 2 or text in stop:",
        "        continue",
        "    out.add(text)",
        "return sorted(out)",
    ])


def semantic_body_windowed_deltas() -> str:
    return body_from_lines([
        "lo, hi = other[:2] if isinstance(other, (list, tuple)) and len(other) >= 2 else (float('-inf'), float('inf'))",
        "values = []",
        "for value in data or []:",
        "    try:",
        "        values.append(min(max(float(value), lo), hi))",
        "    except Exception:",
        "        continue",
        "return [values[i + 1] - values[i] for i in range(len(values) - 1)]",
    ])


def semantic_body_balanced_brackets() -> str:
    return body_from_lines([
        "pairs = {')': '(', ']': '[', '}': '{'}",
        "stack = []",
        "for ch in str(data):",
        "    if ch in '([{':",
        "        stack.append(ch)",
        "    elif ch in pairs:",
        "        if not stack or stack[-1] != pairs[ch]:",
        "            return False",
        "        stack.pop()",
        "return not stack",
    ])


def semantic_body_stdin_pair_sums() -> str:
    return body_from_lines([
        "out = []",
        "for line in str(data).splitlines():",
        "    parts = line.split()",
        "    if len(parts) < 2:",
        "        continue",
        "    try:",
        "        out.append(str(int(parts[0]) + int(parts[1])))",
        "    except Exception:",
        "        continue",
        "return '\\n'.join(out)",
    ])


def semantic_body_stdin_numeric_parse() -> str:
    return body_from_lines([
        "out = []",
        "for line in str(data).splitlines():",
        "    parts = line.split()",
        "    if not parts:",
        "        continue",
        "    try:",
        "        out.append(int(parts[0]))",
        "    except Exception:",
        "        continue",
        "return out",
    ])


def semantic_body_graph_components() -> str:
    return body_from_lines([
        "graph = [[] for _ in range(max(0, int(data)))]",
        "for edge in other or []:",
        "    if not isinstance(edge, (list, tuple)) or len(edge) < 2:",
        "        continue",
        "    try:",
        "        a, b = int(edge[0]), int(edge[1])",
        "    except Exception:",
        "        continue",
        "    if 0 <= a < len(graph) and 0 <= b < len(graph):",
        "        graph[a].append(b)",
        "        graph[b].append(a)",
        "seen = set()",
        "components = 0",
        "for start in range(len(graph)):",
        "    if start in seen:",
        "        continue",
        "    components += 1",
        "    stack = [start]",
        "    seen.add(start)",
        "    while stack:",
        "        node = stack.pop()",
        "        for nxt in graph[node]:",
        "            if nxt not in seen:",
        "                seen.add(nxt)",
        "                stack.append(nxt)",
        "return components",
    ])


def semantic_body_shortest_hops() -> str:
    return body_from_lines([
        "from collections import deque",
        "start = extra[0] if len(extra) > 0 else 0",
        "goal = extra[1] if len(extra) > 1 else 0",
        "graph = [[] for _ in range(max(0, int(data)))]",
        "for edge in other or []:",
        "    if not isinstance(edge, (list, tuple)) or len(edge) < 2:",
        "        continue",
        "    try:",
        "        a, b = int(edge[0]), int(edge[1])",
        "    except Exception:",
        "        continue",
        "    if 0 <= a < len(graph) and 0 <= b < len(graph):",
        "        graph[a].append(b)",
        "        graph[b].append(a)",
        "if start < 0 or goal < 0 or start >= len(graph) or goal >= len(graph):",
        "    return -1",
        "queue = deque([(start, 0)])",
        "seen = {start}",
        "while queue:",
        "    node, dist = queue.popleft()",
        "    if node == goal:",
        "        return dist",
        "    for nxt in graph[node]:",
        "        if nxt not in seen:",
        "            seen.add(nxt)",
        "            queue.append((nxt, dist + 1))",
        "return -1",
    ])


def semantic_body_max_non_adjacent_sum() -> str:
    return body_from_lines([
        "take = 0",
        "skip = 0",
        "for value in data or []:",
        "    value = max(0, int(value))",
        "    take, skip = skip + value, max(skip, take)",
        "return max(take, skip)",
    ])


def semantic_body_lcs_length() -> str:
    return body_from_lines([
        "a = str(data)",
        "b = str(other)",
        "prev = [0] * (len(b) + 1)",
        "for ch_a in a:",
        "    cur = [0]",
        "    for j, ch_b in enumerate(b, 1):",
        "        if ch_a == ch_b:",
        "            cur.append(prev[j - 1] + 1)",
        "        else:",
        "            cur.append(max(prev[j], cur[-1]))",
        "    prev = cur",
        "return prev[-1]",
    ])


def semantic_body_merge_intervals() -> str:
    return body_from_lines([
        "intervals = []",
        "for item in data or []:",
        "    if isinstance(item, (list, tuple)) and len(item) >= 2:",
        "        a, b = item[0], item[1]",
        "        if b > a:",
        "            intervals.append((a, b))",
        "merged = []",
        "for a, b in sorted(intervals):",
        "    if not merged or a > merged[-1][1]:",
        "        merged.append([a, b])",
        "    else:",
        "        merged[-1][1] = max(merged[-1][1], b)",
        "return [tuple(item) for item in merged]",
    ])


def semantic_body_interval_coverage() -> str:
    return body_from_lines([
        "intervals = []",
        "for item in data or []:",
        "    if isinstance(item, (list, tuple)) and len(item) >= 2 and item[1] > item[0]:",
        "        intervals.append((item[0], item[1]))",
        "merged = []",
        "for a, b in sorted(intervals):",
        "    if not merged or a > merged[-1][1]:",
        "        merged.append([a, b])",
        "    else:",
        "        merged[-1][1] = max(merged[-1][1], b)",
        "return sum(b - a for a, b in merged)",
    ])


def semantic_body_longest_even_run() -> str:
    return body_from_lines([
        "best = 0",
        "current = 0",
        "for value in data or []:",
        "    if int(value) % 2 == 0:",
        "        current += 1",
        "        best = max(best, current)",
        "    else:",
        "        current = 0",
        "return best",
    ])


def semantic_body_rle_encode() -> str:
    return body_from_lines([
        "out = []",
        "for item in data or []:",
        "    if out and out[-1][0] == item:",
        "        out[-1] = (item, out[-1][1] + 1)",
        "    else:",
        "        out.append((item, 1))",
        "return out",
    ])


def semantic_body_threshold_labels() -> str:
    return body_from_lines([
        "out = []",
        "for record in data or []:",
        "    if not isinstance(record, dict):",
        "        continue",
        "    try:",
        "        score = float(record.get('score', 0))",
        "    except Exception:",
        "        score = 0.0",
        "    if score >= other and record.get('label') is not None:",
        "        out.append(str(record.get('label')))",
        "return out",
    ])


def semantic_body_top_k_frequent() -> str:
    return body_from_lines([
        "counts = {}",
        "for item in data or []:",
        "    counts[item] = counts.get(item, 0) + 1",
        "items = sorted(counts, key=lambda key: (-counts[key], key))",
        "return items[:max(0, int(other))]",
    ])


def semantic_body_media_preview_index() -> str:
    return body_from_lines([
        "query = other if isinstance(other, dict) else {}",
        "need_tags = set(query.get('tags') or [])",
        "album = query.get('album')",
        "hits = []",
        "for item in data or []:",
        "    if not isinstance(item, dict):",
        "        continue",
        "    if album and item.get('album') != album:",
        "        continue",
        "    tags = set(item.get('tags') or [])",
        "    if not need_tags <= tags:",
        "        continue",
        "    hits.append((str(item.get('date') or ''), str(item.get('id') or '')))",
        "return [media_id for _date, media_id in sorted(hits, reverse=True) if media_id]",
    ])


def semantic_body_room_capability_summary() -> str:
    return body_from_lines([
        "rooms = {}",
        "for node in data or []:",
        "    if not isinstance(node, dict):",
        "        continue",
        "    room = str(node.get('room') or 'unknown')",
        "    rec = rooms.setdefault(room, {'devices': 0, 'mics': 0, 'speakers': 0})",
        "    rec['devices'] += 1",
        "    if node.get('mic'):",
        "        rec['mics'] += 1",
        "    if node.get('speaker'):",
        "        rec['speakers'] += 1",
        "return {room: rooms[room] for room in sorted(rooms)}",
    ])


def semantic_body_memory_latest_by_project() -> str:
    return body_from_lines([
        "latest = {}",
        "for item in data or []:",
        "    if not isinstance(item, dict):",
        "        continue",
        "    project = item.get('project')",
        "    text = item.get('text')",
        "    ts = item.get('ts', 0)",
        "    if not project or text is None:",
        "        continue",
        "    old = latest.get(project)",
        "    if old is None or ts >= old[0]:",
        "        latest[project] = (ts, text)",
        "return {key: value[1] for key, value in sorted(latest.items())}",
    ])


def semantic_body_memory_open_action_rollup() -> str:
    return body_from_lines([
        "out = {}",
        "for item in data or []:",
        "    if not isinstance(item, dict) or item.get('done'):",
        "        continue",
        "    owner = item.get('owner') or 'unassigned'",
        "    label = item.get('label')",
        "    if not label:",
        "        continue",
        "    out.setdefault(owner, set()).add(str(label))",
        "return {owner: sorted(labels) for owner, labels in sorted(out.items())}",
    ])


def semantic_body_storage_quota_select() -> str:
    return body_from_lines([
        "quota = int(other or 0)",
        "items = []",
        "for item in data or []:",
        "    if not isinstance(item, dict):",
        "        continue",
        "    name = item.get('name')",
        "    size = int(item.get('size') or 0)",
        "    priority = int(item.get('priority') or 0)",
        "    if not name or size <= 0 or size > quota:",
        "        continue",
        "    items.append((-priority, size, str(name)))",
        "used = 0",
        "picked = []",
        "for _prio, size, name in sorted(items):",
        "    if used + size <= quota:",
        "        picked.append(name)",
        "        used += size",
        "return picked",
    ])


def semantic_body_storage_sync_plan() -> str:
    return body_from_lines([
        "ops = []",
        "local = data if isinstance(data, dict) else {}",
        "remote = other if isinstance(other, dict) else {}",
        "for path in sorted(set(local) | set(remote)):",
        "    left = local.get(path)",
        "    right = remote.get(path)",
        "    if left is None:",
        "        ops.append(('download', path))",
        "    elif right is None:",
        "        ops.append(('upload', path))",
        "    elif left != right:",
        "        ops.append(('upload', path))",
        "return ops",
    ])


def semantic_body_device_route_worker() -> str:
    return body_from_lines([
        "request = other if isinstance(other, dict) else {}",
        "need = set(request.get('capabilities') or [])",
        "best = None",
        "for node in data or []:",
        "    if not isinstance(node, dict):",
        "        continue",
        "    caps = set(node.get('capabilities') or [])",
        "    if not need <= caps:",
        "        continue",
        "    if request.get('avoid_battery') and node.get('battery') is True:",
        "        continue",
        "    score = (float(node.get('latency_ms') or 999999), -float(node.get('memory_gb') or 0), str(node.get('name') or ''))",
        "    if best is None or score < best[0]:",
        "        best = (score, str(node.get('name') or ''))",
        "return best[1] if best else ''",
    ])


def semantic_body_voice_output_route() -> str:
    return body_from_lines([
        "room = str(other or '')",
        "best = None",
        "for node in data or []:",
        "    if not isinstance(node, dict) or not node.get('speaker'):",
        "        continue",
        "    closeness = 0 if str(node.get('room') or '') == room else 1",
        "    confidence = -float(node.get('confidence') or 0)",
        "    latency = float(node.get('latency_ms') or 999999)",
        "    score = (closeness, confidence, latency, str(node.get('name') or ''))",
        "    if best is None or score < best[0]:",
        "        best = (score, str(node.get('name') or ''))",
        "return best[1] if best else ''",
    ])


def semantic_body_plan_next_unblocked() -> str:
    return body_from_lines([
        "done = {str(item.get('id')) for item in data or [] if isinstance(item, dict) and item.get('done')}",
        "available = []",
        "for item in data or []:",
        "    if not isinstance(item, dict) or item.get('done'):",
        "        continue",
        "    deps = {str(dep) for dep in item.get('deps') or []}",
        "    if deps <= done:",
        "        available.append((-int(item.get('priority') or 0), str(item.get('id') or '')))",
        "return [task_id for _prio, task_id in sorted(available) if task_id]",
    ])


def semantic_body_plan_progress_digest() -> str:
    return body_from_lines([
        "out = {'blocked': 0, 'done': 0, 'open': 0, 'owners': []}",
        "owners = set()",
        "for item in data or []:",
        "    if not isinstance(item, dict):",
        "        continue",
        "    if item.get('done'):",
        "        out['done'] += 1",
        "    elif item.get('blocked'):",
        "        out['blocked'] += 1",
        "    else:",
        "        out['open'] += 1",
        "        if item.get('owner'):",
        "            owners.add(str(item.get('owner')))",
        "out['owners'] = sorted(owners)",
        "return out",
    ])


def semantic_body_generic_list_append() -> str:
    return body_from_lines([
        "out = []",
        "for item in data or []:",
        "    if item is None:",
        "        continue",
        "    out.append(item)",
        "return out",
    ])


def semantic_body_generic_dict_group_append() -> str:
    return body_from_lines([
        "out = {}",
        "for item in data or []:",
        "    if not isinstance(item, dict):",
        "        continue",
        "    key = item.get('key') or item.get('project') or item.get('owner') or 'unknown'",
        "    value = item.get('value', item)",
        "    out.setdefault(str(key), []).append(value)",
        "return out",
    ])


def semantic_body_generic_set_add() -> str:
    return body_from_lines([
        "out = set()",
        "for item in data or []:",
        "    out.add(item)",
        "return sorted(out)",
    ])


def semantic_body_generic_return() -> str:
    return body_from_lines([
        "return data",
    ])


def render_statement_skeleton_body(tokens: list[str]) -> tuple[str, dict[str, Any]]:
    skeleton = []
    for tok in tokens:
        if tok == "<eos>":
            break
        if tok.startswith("SKEL:"):
            skeleton.append(tok)
    shape = decoded_return_shape(skeleton)
    has_loop = any(tok in {"SKEL:LOOP_DATA", "SKEL:LOOP_OTHER", "SKEL:LOOP_WHILE"} for tok in skeleton)
    has_branch = "SKEL:BRANCH_GUARD" in skeleton
    has_try = "SKEL:TRY_EXCEPT" in skeleton
    has_append = "SKEL:CALL_APPEND" in skeleton
    lines: list[str] = []
    if shape:
        lines.extend(initializer_for_shape(shape))
    elif has_loop:
        lines.append("result = []")
    elif any(tok.startswith("SKEL:ASSIGN_") for tok in skeleton):
        lines.append("result = None")
    if has_loop:
        lines.append("for item in data:")
        loop_indent = "    "
        if has_branch:
            lines.append(f"{loop_indent}if item is None:")
            lines.append(f"{loop_indent}    continue")
        if has_try:
            lines.append(f"{loop_indent}try:")
            for line in update_lines_for_shape(shape or "unknown", has_append=has_append):
                lines.append(f"{loop_indent}    {line}")
            lines.append(f"{loop_indent}except Exception:")
            lines.append(f"{loop_indent}    continue")
        else:
            for line in update_lines_for_shape(shape or "unknown", has_append=has_append):
                lines.append(f"{loop_indent}{line}")
    elif has_branch:
        lines.append("if data:")
        lines.append("    result = data")
    if shape:
        lines.append(return_line_for_shape(shape))
    body = "\n".join(lines).strip()
    return body, {
        "rendered_from_statement_skeleton": True,
        "skeleton_token_count": len(skeleton),
        "unique_skeleton_tokens": sorted(set(skeleton)),
        "predicted_return_shape": shape or "",
        "predicted_loop": has_loop,
        "predicted_branch": has_branch,
        "predicted_try": has_try,
        "predicted_append": has_append,
        "rendered_line_count": len(lines),
    }


def decoded_return_shape(skeleton: list[str]) -> str:
    for tok in skeleton:
        if tok.startswith("SKEL:RETURN_"):
            shape = tok.removeprefix("SKEL:RETURN_").lower()
            if shape in {"list", "dict", "set", "tuple", "number", "bool", "str", "none", "unknown"}:
                return shape
    return ""


def initializer_for_shape(shape: str) -> list[str]:
    if shape == "dict":
        return ["result = {}"]
    if shape == "set":
        return ["result = set()"]
    if shape == "tuple":
        return ["result = []"]
    if shape == "number":
        return ["result = 0"]
    if shape == "bool":
        return ["result = False"]
    if shape == "str":
        return ["result = ''"]
    if shape == "none":
        return []
    return ["result = []"]


def update_lines_for_shape(shape: str, *, has_append: bool) -> list[str]:
    if shape == "dict":
        return ["result[str(item)] = item"]
    if shape == "set":
        return ["result.add(item)"]
    if shape == "tuple":
        return ["result.append(item)"]
    if shape == "number":
        return ["result += int(item)"]
    if shape == "bool":
        return ["if item:", "    result = True"]
    if shape == "str":
        return ["result += str(item)"]
    if has_append or shape in {"list", "unknown", ""}:
        return ["result.append(item)"]
    return ["result = item"]


def return_line_for_shape(shape: str) -> str:
    if shape == "tuple":
        return "return tuple(result)"
    if shape == "bool":
        return "return bool(result)"
    if shape == "none":
        return "return None"
    if shape == "unknown":
        return "return result"
    return "return result"


def normalize_body_text(body: str) -> str:
    body = textwrap.dedent(str(body or ""))
    lines = []
    for raw in body.replace("\r\n", "\n").replace("\r", "\n").splitlines():
        line = raw.replace("\t", "    ").rstrip()
        if line.strip():
            lines.append(line)
    return "\n".join(lines).strip()


def token_values_to_line(values: list[str]) -> str:
    out = ""
    prev = ""
    binary_ops = {
        "=",
        "+",
        "-",
        "*",
        "/",
        "//",
        "%",
        "**",
        "==",
        "!=",
        "<",
        "<=",
        ">",
        ">=",
        "and",
        "or",
        "in",
        "is",
        "not",
    }
    no_space_before = {")", "]", "}", ",", ":", ".", ";"}
    no_space_after = {"(", "[", "{", ".", "@"}
    for raw in values:
        value = str(raw or "")
        if not value:
            continue
        if not out:
            out = value
        elif value in no_space_before:
            out += value
        elif prev in no_space_after:
            out += value
        elif value == "(" and (prev.isidentifier() or prev in {")", "]", "}"}):
            out += value
        elif value in binary_ops or prev in binary_ops:
            out += " " + value
        else:
            out += " " + value
        prev = value
    return out
